### ISSUE TITLE
XAML samples

### ISSUE THREAD

**Issue by rubgithub** [daniel-luberda/DLToolkit.Forms.Controls#1]
Hi, thanks for this component.

Could you provide a full XAML sample?  (FlowListView)

I'm trying to understand the code behind by is very difficult.

`
<controls1:FlowStackCell Orientation="Horizontal">
                <controls1:FlowStackCell.Children>
                    <Label Text="{Binding Name}"></Label>                                                           
                </controls1:FlowStackCell.Children>
            </controls1:FlowStackCell> 
`

**Comment by daniel-luberda** [comment]
FlowListView is just a ListView, it's a custom control, so you must use prefixes with correct namespaces defined (as any custom control in XAML). You do almost everything just the same as normal list view. 

FlowStackCell is just a predefined custom cell template which is a StackLayout (you don't need to use it, you can create your own view). 

Full XAML example is here: 
- [FlowListViewExpandPage.xaml](https://github.com/daniel-luberda/DLToolkit.Forms.Controls/blob/master/Examples/Pages/FlowListViewExpandPage.xaml)
- [FlowListViewExpandPage.xaml.cs](https://github.com/daniel-luberda/DLToolkit.Forms.Controls/blob/master/Examples/Pages/FlowListViewExpandPage.xaml.cs)
- [FlowListViewViewModel.cs](https://github.com/daniel-luberda/DLToolkit.Forms.Controls/blob/master/Examples/ViewModels/FlowListViewViewModel.cs)

and custom cell template used in example: 
- [FlowListViewExpandCell.xaml](https://github.com/daniel-luberda/DLToolkit.Forms.Controls/blob/master/Examples/Views/FlowListViewExpandCell.xaml)
- [FlowListViewExpandCell.cs](https://github.com/daniel-luberda/DLToolkit.Forms.Controls/blob/master/Examples/Views/FlowListViewExpandCell.xaml.cs)

**Comment by rubgithub** [comment]
Thanks.
