### ISSUE TITLE
TemplateSelector different FlowColumnCount for first row

### ISSUE THREAD

**Issue by simonedoria** [daniel-luberda/DLToolkit.Forms.Controls#100]
Hi,
I implemented the TemplateSelector and it's working fine.
But i have a problem that i'm unable to resolve.
Simply i want the FIRST element of my collection to be FULL WIDTH in the first row (FlowColumnCount = 1), and the others elements splitted in 3 columns (FlowColumnCount = 3).

It can be done?

Thanks

**Comment by simonedoria** [comment]
Solved by putting the Header in it.
<flv:FlowListView.Header>
        <View />
</flv:FLowListView.Header>

**Comment by daniel-luberda** [comment]
Ok, glad to hear that you worked it out. Cheers :) There's also a new way of achieving it (for each row separately): https://github.com/daniel-luberda/DLToolkit.Forms.Controls/blob/master/Samples/DLToolkitControlsSamples/SamplesFlowListView/GroupingAdvancedPage.xaml#L14
