### ISSUE TITLE
Pulltorefresh not working (android)

### ISSUE THREAD

**Issue by raymondjstone** [daniel-luberda/DLToolkit.Forms.Controls#106]
Added pulltorefresh on existing working Xamarin.Forms app (at the moment only the Android branch is being developed, the UWP and IOS ones are a secondary update project).

Code additions shown below

When the pull gesture is used the indictator for it appears but NONE of the code added is actually run

On the output log this message appears

D/ViewRootImpl(20424): ViewPostImeInputStage ACTION_DOWN

(this appears even when the pulldown funtions are NOT added to the control)

The indicator remains on screen all the time and no application code is triggered.

Added to the XAML

RefreshCommand="{Binding RefreshCommand}"
            IsRefreshing="{Binding IsRefreshing}"
            IsPullToRefreshEnabled="True"

And to the code

private bool _isRefreshing = false;
        public bool IsRefreshing
        {
            get { return _isRefreshing; }
            set
            {
                _isRefreshing = value;
                OnPropertyChanged(nameof(IsRefreshing));
            }
        }
        public ICommand RefreshCommand
        {
            get
            {
                return new Command(async () =>
                {
                    IsRefreshing = true;

                    await App.RefreshApplicationData();

                    IsRefreshing = false;
                });
            }
        }

**Comment by raymondjstone** [comment]
Also not working on UWP

**Comment by thetombomb91** [comment]
I have it working in a small sample project with the following code 

XAML
    

        IsPullToRefreshEnabled="true"

        RefreshCommand="{Binding PullToRefresh}"

        IsRefreshing="{Binding RefreshActive}"


ViewModel

        public DelegateCommand PullToRefresh { get; set; }

        public SimpleSamplePageViewModel()

        {

            PullToRefresh = new DelegateCommand(OnPullToRefresh);

            GenerateSimpleItems();

        }

        private bool _RefreshActive;

        public bool RefreshActive

        {

            get { return _RefreshActive; }

            set { SetProperty(ref _RefreshActive, value); }

        }


        private void OnPullToRefresh()

        {

            RefreshActive = false;

        }


Check out the full view model here https://github.com/thetombomb91/FlowListViewSampleApp/blob/master/FlowListViewSampleApp/FlowListViewSampleApp/ViewModels/SimpleSamplePageViewModel.cs

and full view here https://github.com/thetombomb91/FlowListViewSampleApp/blob/master/FlowListViewSampleApp/FlowListViewSampleApp/Views/SimpleSamplePage.xaml

**Comment by daniel-luberda** [comment]
`PullToRefresh` is the same implementation as in `Xamarin.Forms.ListView`. It's definitely not an `FlowListView` issue. Cheers.

**Comment by prom3theu5** [comment]
Is this still the case?
I'm seeing the same issue

Also - the example above doesn't actually update anything. It loads data once in your viewmodel constructor.

VM:

```csharp
 public class MainPageViewModel : ViewModelBase
    {
        public ObservableCollection<Video> Videos { get; set; }
        public Video SelectedVideo { get; set; }
        public bool IsRefreshing { get; set; }
        public DelegateCommand RefreshVideosCommand { get; set; }
        public DelegateCommand VideoTappedCommand { get; set; }
        private readonly IPageDialogService _dialogService;
        private readonly IDataStore<Video> _dataStore;

        public MainPageViewModel(
            INavigationService navigationService, 
            IPageDialogService dialogService,
            IDataStore<Video> dataStore) 
            : base (navigationService)
        {
            _dialogService = dialogService;
            _dataStore = dataStore;
            VideoTappedCommand = new DelegateCommand(SelectVideo);
            RefreshVideosCommand = new DelegateCommand(RefreshVideos);
            Videos = new ObservableCollection<Video>();
            IsRefreshing = false;
            RefreshVideos();
        }

        public async void RefreshVideos()
        {
            if (IsRefreshing) return;

            IsRefreshing = true;

            Videos.Clear();
            var _videos = await _dataStore.GetVideosAsync(true);

            foreach (var video in _videos)
            {
                if (string.IsNullOrWhiteSpace(video.Thumbnail))
                    Videos.Add(new Video(video.Url, video.Title));
                else
                    Videos.Add(video);
            }

            IsRefreshing = false;
        }

        private async void SelectVideo()
        {
            if (SelectedVideo == null) return;
            try
            {
                var videoParameters = new NavigationParameters
                {
                    { "videoUrl", SelectedVideo.Url }
                };

                await NavigationService.NavigateAsync("VideoPlayerPage", videoParameters, false, true);
            }
            catch (Exception ex)
            {
                await _dialogService.DisplayAlertAsync("Error Playing Video", ex.Message, "OK");
                Debug.WriteLine(await Task.Run(() => JsonConvert.SerializeObject(SelectedVideo)));
            }
        }
```

View:

```csharp
 <StackLayout HorizontalOptions="Fill" VerticalOptions="Fill">

        <flv:FlowListView SeparatorVisibility="None" HasUnevenRows="true"
			FlowItemTappedCommand="{Binding VideoTappedCommand}" FlowLastTappedItem="{Binding SelectedVideo}"
			FlowColumnMinWidth="300" FlowItemsSource="{Binding Videos}"
            IsPullToRefreshEnabled="True" RefreshCommand="{Binding RefreshVideosCommand}" IsRefreshing="{Binding IsRefreshing}">

            <flv:FlowListView.FlowColumnTemplate>
                <DataTemplate>
                    <Grid Padding="20">

                        <Grid.RowDefinitions>
                            <RowDefinition Height="*" />
                        </Grid.RowDefinitions>
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition Width="*" />
                        </Grid.ColumnDefinitions>

                        <ffimageloading:CachedImage HeightRequest="250" Aspect="AspectFill"
							DownsampleHeight="250" DownsampleUseDipUnits="false" 
							LoadingPlaceholder="image_loading.png" ErrorPlaceholder="image_error.png"
                            Source="{Binding Thumbnail}"/>
                        
                    </Grid>
                </DataTemplate>
            </flv:FlowListView.FlowColumnTemplate>

        </flv:FlowListView>

    </StackLayout>
```

What happens is the refresh starts, but IsRefreshing never gets updated to false, and so the refreshing symbol stays on the screen
Android 6.0

**Comment by Giorgi** [comment]
@prom3theu5 The reason the symbol stays on is that you are not setting BindingContext for the `IsRefreshing` binding. If you change the binding to `IsRefreshing="{Binding IsRefreshing, Source={x:Reference Page}}` and add `x:Name="Page"` to the `ContentPage` tag it will work correctly
