### ISSUE TITLE
Support macOS with Xamarin.Forms 2.3.5 on Xamarin.Mac V2.0

### ISSUE THREAD

**Issue by YZahringer** [daniel-luberda/DLToolkit.Forms.Controls#107]
Currently support for macOS by Xamarin is in beta with version 2.3.5. Would it be possible to provide a pre-release with macOS support?

**Comment by YZahringer** [comment]
Only a rebuild with latest version of Visual Studio 2017 is required, all works on MacOS with new binaries. Can you publish a new nuget version?

**Comment by daniel-luberda** [comment]
Done. New nuget coming soon.  :)
