### ISSUE TITLE
Grouping example corrupted in Android 7.1

### ISSUE THREAD

**Issue by pzs7602** [daniel-luberda/DLToolkit.Forms.Controls#108]
When choosing grouping example in project, scroll the screen, the app is corrupted. My phone is Google Pixel running Android 7.1.2. The error is the same on other Android devices running Android 7.0+
The error message:
System.NullReferenceException
Object reference not set to an instance of an object

**Comment by daniel-luberda** [comment]
Could you post full stack trace?

**Comment by daniel-luberda** [comment]
Duplicate of https://github.com/daniel-luberda/DLToolkit.Forms.Controls/issues/65
