### ISSUE TITLE
FlowListView, chance of scrolling x and y so it can cope with many columns?

### ISSUE THREAD

**Issue by Yumeryu** [daniel-luberda/DLToolkit.Forms.Controls#11]
Hi Daniel, 

thanks a lot for the great project. it's very easy to use and it looks great. 

However, I'm currently facing one big issue I'm not sure how to solve. Any pointers will be greatly appreciated. 

Current FlowListView work great with a few columns, however when there are a lot of columns, it squeeze them all in one page width, and make it impossible to read. 

So, is there any chance of scrolling x and y so it can cope with many columns?

Thanks in advance.

**Comment by daniel-luberda** [comment]
@Yumeryu Thanks. You can set `FlowAutoColumnCount` to `true` and `FlowColumnDefaultMinimumWidth` property. Column count will be calculated automatically. Does it solve your issue?

**Comment by Yumeryu** [comment]
Thanks for your quick reply. 

I have tried those settings, they are recalculating all the columns and still fit them in one page. So this will lose the columns mapping. 

What I'm trying to achieve is, for example, I have 12 columns for each month, and I want to list each row with all 12 columns, and if it doesn't fit in one page, I would expect the FlowListView to expand over the page, so I can scroll from left to right to see all columns, and scroll from top to bottom to see all rows. 

I'm not sure if this is achievable at the moment, and how complicated to mod code to achieve this?

Thanks in advance.

**Comment by daniel-luberda** [comment]
@Yumeryu I think it's possible but I'll need to modify a FlowListView a bit.

https://github.com/daniel-luberda/DLToolkit.Forms.Controls/blob/master/FlowListView/DLToolkit.Forms.Controls.FlowListView/FlowListViewInternalCell.cs#L43

Basically, this:  

`View = rootLayout;`

Needs to be changed to: 

`View = new ScrollView() { View = rootLayout; };`

I'll need to introduce some property for that as in normal use cases using `ScrollView` could be not good for performance reasons.

**Comment by Yumeryu** [comment]
Again, thanks a lot for the quick reply. 

I just gave that a quick try. 
Replaced with this :
			View = new ScrollView
			{
				Content = rootLayout
			};


However, the layout of the view hasn't changed, the performance did drop as you mentioned. I tried both with settings FlowAutoColumnCount to true and FlowColumnDefaultMinimumWidth, and without.

**Comment by daniel-luberda** [comment]
It's definitely possible, but I'll need to check if all the other `LayoutOptions` are correct, etc. And you also need to set correct ScrollView orientation. I can implement it, but definitely not today.

**Comment by Yumeryu** [comment]
Sure, thanks a lot. 

In the mean time, I will try to see if i can find how these LayoutOptions and ScrollView works. Any pointers will be greatly appreciated.

**Comment by daniel-luberda** [comment]
I think it can be because of using `AbsoluteLayout` (for performance reasons). I think for such case `StackLayout` + `ScrollView` would be a better solution. So it means it's better and easier to make a new internal cell implementation eg. `FlowListViewScrolledInternalCell` and basically all those calculations are not needed, just simple add / remove from `StackLayout`

**Comment by daniel-luberda** [comment]
@Yumeryu Did you have any success implementing this?

**Comment by reynzmonaresgithub** [comment]
..hello @daniel-luberda , how can I set FlowAutoColumnCount in FlowListView? It seems that this property is not available currently. thanks
