### ISSUE TITLE
How to hide scrollbars?

### ISSUE THREAD

**Issue by peppe130** [daniel-luberda/DLToolkit.Forms.Controls#110]
Hi,

I'm using the latest version of this library in my cross-platform PCL project. How can I hide the scrollbar that appears when scrolling the list? Thanks!

**Comment by zanesc** [comment]
I would like this as well.

**Comment by daniel-luberda** [comment]
You must create custom renderer for a `FlowListView`, just inherit from `ListViewRenderer`.  (as it's platform specific).

**Comment by daniel-luberda** [comment]
https://stackoverflow.com/questions/32067257/xamarin-forms-hiding-the-scrollbar-in-a-listview
