### ISSUE TITLE
Problem to set FlowColumnMinWidth using Style

### ISSUE THREAD

**Issue by leovictor** [daniel-luberda/DLToolkit.Forms.Controls#111]
I'm using Xamarin.Forms. If I try to set this property using style in App.xaml.cs (Setter Property="FlowColumnMinWidth" Value="120") the FlowListView use the default value (50d). Is it a issue or the problem it's me ? 😄 (PS: If I create a resource inside App.xaml.cs and use FlowColumnMinWidth="{StaticResource DefaultFlowColumnWidth}" in FlowListView the Page it work well)

**Comment by daniel-luberda** [comment]
`FlowColumnMinWidth` is just a standard bindable property. It's hard to help with some more code. If it's not working, it's probably not a `FlowListView` issue.
