### ISSUE TITLE
FlowListView with SwitchCell

### ISSUE THREAD

**Issue by chuckles2405** [daniel-luberda/DLToolkit.Forms.Controls#112]
I'm obviously not doing something correctly.  I have a SwitchCell (with grouping) as the sole item in the DataTemplate of the FlowListView.  It is showing the Group Name, but is not showing any of the switchCells.  Previously I had this project in Xamarin Forms and it performs correctly.  I would like to use FlowListView to show multiple Maintenance Items.

Here is my XAML Snippet:

<flv:FlowListView x:Name="listView" FlowColumnCount="6" SeparatorVisibility="Default" RowHeight="100" ItemsSource="{Binding groupedData}" 
FlowUseAbsoluteLayoutInternally="false" FlowColumnExpand="None" IsGroupingEnabled="true" FlowGroupDisplayBinding="{Binding Key}" FlowGroupShortNameBinding="{Binding Key}" >

 <flv:FlowListView.FlowColumnTemplate>
     <DataTemplate>
      <SwitchCell  Text="{Binding MaintenanceItem}"   On="{Binding IsOn}"   />
     </DataTemplate>
 </flv:FlowListView.FlowColumnTemplate>
 </flv:FlowListView>

Please forgive my obvious "newness".  I'm relatively new to Xamarin.

**Comment by daniel-luberda** [comment]
When using FlowListView you can't use `ViewCells` (and `SwitchCell` is a `ViewCell` too). You need to use `Views`. That's why it's not working for you.
