### ISSUE TITLE
Data page is not loading 

### ISSUE THREAD

**Issue by Afsarunnisa** [daniel-luberda/DLToolkit.Forms.Controls#115]
in my existing app trying to load one page with flowlist view and i am not using Xamvvm. i am replicating same things in SimpleGalleryPage. 

my page 

		<flv:FlowListView SeparatorVisibility="None" HasUnevenRows="true"
			FlowItemTappedCommand="{Binding ItemTappedCommand}" FlowLastTappedItem="{Binding LastTappedItem}"
			FlowColumnMinWidth="200" FlowItemsSource="{Binding Items}">

			<flv:FlowListView.FlowColumnTemplate>
				<DataTemplate >

					<Grid Padding="2">
						
						<Grid.RowDefinitions>
							<RowDefinition Height="*" />
						</Grid.RowDefinitions>

                        <Grid.ColumnDefinitions>
							<ColumnDefinition Width="*" />
						</Grid.ColumnDefinitions>
						
						<ffimageloading:CachedImage HeightRequest="200" WidthRequest = "350" Aspect="AspectFill"
							DownsampleHeight="200" DownsampleUseDipUnits="false" 
							LoadingPlaceholder="image_loading.png" ErrorPlaceholder="image_error.png"
							Source="{Binding ImageUrl}"/>

						<Label x:Name="Label" HorizontalOptions="Fill" HorizontalTextAlignment="Center" VerticalTextAlignment="Center" VerticalOptions="End" HeightRequest = "50"
							BackgroundColor="Silver" Opacity="0.5" Text="{Binding FileName}"/>
					</Grid>
				</DataTemplate>
			</flv:FlowListView.FlowColumnTemplate>
		
		</flv:FlowListView>

.cs

			var viewModel = new ProductsViewModel();
			viewModel.ReloadData();

View model:

		public void ReloadData()
		{
			var list = new List<ItemModel>();

			string[] images = {
						"https://farm9.staticflickr.com/8625/15806486058_7005d77438.jpg",
						"https://farm5.staticflickr.com/4011/4308181244_5ac3f8239b.jpg",
						"https://farm8.staticflickr.com/7423/8729135907_79599de8d8.jpg",
						"https://farm3.staticflickr.com/2475/4058009019_ecf305f546.jpg",
						"https://farm6.staticflickr.com/5117/14045101350_113edbe20b.jpg",
						"https://farm2.staticflickr.com/1227/1116750115_b66dc3830e.jpg",
						"https://farm8.staticflickr.com/7351/16355627795_204bf423e9.jpg",
						"https://farm1.staticflickr.com/44/117598011_250aa8ffb1.jpg",
						"https://farm8.staticflickr.com/7524/15620725287_3357e9db03.jpg",
						"https://farm9.staticflickr.com/8351/8299022203_de0cb894b0.jpg",
					};

			int number = 0;
			//for (int n = 0; n < 20; n++)
			//{
			for (int i = 0; i < images.Length; i++)
			{
				number++;
				var item = new ItemModel()
				{
					ImageUrl = images[i],
					FileName = string.Format("image_{0}.jpg", number),
				};

				list.Add(item);
			}
			//}

			Debug.WriteLine("list {0}", list);

			Items = list;

			Debug.WriteLine("Items {0}", Items);

		}

		public List<ItemModel> Items;

		public class ItemModel
		{
			//string imageUrl;
			public string ImageUrl { get; set; }
			//{
			//	get { return imageUrl; }
			//	set { SetField(ref imageUrl, value); }
			//}

			//string fileName;
			public string FileName { get; set; }
			//{
			//	get { return fileName; }
			//	set { SetField(ref fileName, value); }
			//}
		}

its not loading page.

**Comment by daniel-luberda** [comment]
You must set page `BindingContext` to you view model instance.

**Comment by anishmm** [comment]
How to add 'ItemTappedCommand' with out Xamvvm ?

**Comment by daniel-luberda** [comment]
It's just a standard Xamarin binding, no Xamvvm needed. https://developer.xamarin.com/guides/xamarin-forms/xaml/xaml-basics/data_binding_basics/
