### ISSUE TITLE
Samples not running - The XamlCTask failed Unexpectedly - DLToolkit.Forms.Controls.FlowListView.dll.mdb not found

### ISSUE THREAD

**Issue by sskohli** [daniel-luberda/DLToolkit.Forms.Controls#116]
Hi,
I am running the samples on Visual Studio 7.0.1 for Mac. I get the following 2 build errors 
```
<Target Name="XamlC">
		<XamlCTask
			Assembly = "$(IntermediateOutputPath)$(TargetFileName)"
			ReferencePath = "@(ReferencePath)"
			Verbosity = "2"
			OptimizeIL = "true"
			DebugSymbols = "$(DebugSymbols)" />
	</Target>
```
/Projects/DLToolkit.Forms.Controls-master/FlowListView/DLToolkit.Forms.Controls.FlowListView/obj/Debug/DLToolkit.Forms.Controls.FlowListView.dll.mdb

**Comment by thetombomb91** [comment]
Have you updated Xamarin.Forms to the latest version?

**Comment by Vinnie1991** [comment]
I can confirm. I had the same issue with running the samples.
After I updated Xamarin.Forms to the latest version (2.3.4.247 at this time) I could run the samples
