### ISSUE TITLE
UWP Label Binding Issue

### ISSUE THREAD

**Issue by JeffB1** [daniel-luberda/DLToolkit.Forms.Controls#117]
In the DataTemplate I set up a Label which is bound to a property of an object. When I change the property I would expect the binding would fire and the label would update. It does on Android but not on UWP. It's possibly related to this issue with ListView but I wasn't able to use any of those suggested fixes to make it work.

https://forums.xamarin.com/discussion/58266/binding-update-become-blank-on-uwp

**Comment by daniel-luberda** [comment]
`FlowListView` is just `ListView`, so we can't fix it here, as it's probably a Xamarin.Forms layout system issue.
