### ISSUE TITLE
StaticResource not found for key TagValidatorFactory

### ISSUE THREAD

**Issue by mazloumi** [daniel-luberda/DLToolkit.Forms.Controls#118]
Hi, when I try your sample it works but when I use the same example in my project and in the code behind register the TagValidatorFactory resource 

        public MyPage()
        {
			Resources = new ResourceDictionary();
			Resources.Add("Validate", new Func<string, object>(
				(arg) => (BindingContext as FieldsPageViewModel)?.ValidateAndReturn(arg)));
            InitializeComponent();
        }

and use in MyPage.xaml

<dltag:TagEntryView TagItems="{Binding Items}" TagTappedCommand="{Binding RemoveTagCommand}" TagValidatorFactory="{StaticResource TagValidatorFactory}">

I get the error: StaticResource not found for key TagValidatorFactory

Any idea?

**Comment by carl-neng** [comment]
Yes I got like this also. Please help me.

**Comment by daniel-luberda** [comment]
You should change this: 

```XML
<dltag:TagEntryView TagItems="{Binding Items}" TagTappedCommand="{Binding RemoveTagCommand}" TagValidatorFactory="{StaticResource TagValidatorFactory}">
```

Into:

```XML
<dltag:TagEntryView TagItems="{Binding Items}" TagTappedCommand="{Binding RemoveTagCommand}" TagValidatorFactory="{StaticResource Validate}">
```

Because of: 

Resources.Add("**Validate**", new Func<string, object>
