### ISSUE TITLE
Wrong cell size changing orientation of device

### ISSUE THREAD

**Issue by antonardelli** [daniel-luberda/DLToolkit.Forms.Controls#119]
Hello,
I have tried your sample project and I have noticed a strange behaviour.
If I put in images list only 2 elements, put the device in landscape mode, it creates 6 colums. After that, I change orientation and put the device in portrait mode (without closing the page), and the cell width becomes wrong, because is it like it considers 6 cells instead of 3. 
I investigated the problem, and it seems that method RowLayoutChanged returns false and so it does not recreate the layout. But it should be recreated because cells width should be proportional to the new size.
The problem happens only if there are a few elements, that is <= number of column of portrait mode (in my case 2 <= 3). If I put 4 elements in the view, it works correctly.

I attached some screenshots here:

![screenshot_20170802-145511](https://user-images.githubusercontent.com/4288223/28874929-15710e44-7794-11e7-84b2-8cb05d3e0d4e.png)
![screenshot_20170802-145518](https://user-images.githubusercontent.com/4288223/28874931-1997ff46-7794-11e7-89ac-f75889dc0106.png)

Thank you for support!

**Comment by daniel-luberda** [comment]
It should be fixed with: https://github.com/daniel-luberda/DLToolkit.Forms.Controls/commit/91e6119450457e667f69fe4e91c2fde541c4cfc5

Please try the newest nuget and reopen if you still experience it. Thanks.
