### ISSUE TITLE
Image Gallery - Image Truncation

### ISSUE THREAD

**Issue by TimeBomb006** [daniel-luberda/DLToolkit.Forms.Controls#12]
I'm having trouble creating an image gallery using your library. It works well but there are some cosmetic issues that have been problematic..

On first page load, the "Station List" looks good, but is truncated at 6 items (2 rows of pictures). If I navigate back and reload the same page, the "Station List" is fully loaded, but the ListView background extends far down the page (like 3 or 4 'pages' of black nothingness). I've added a black background so that it's obvious what's happening, but I can't figure out how to correct the issue. It's possible that I'm constructing the template ContentView incorrectly, but I'd like to defer to your expertise.

![image](https://cloud.githubusercontent.com/assets/2583638/17121733/af2eec0c-52a3-11e6-8e1d-2ea3861b001c.png)

![image](https://cloud.githubusercontent.com/assets/2583638/17121790/1a970baa-52a4-11e6-939c-32d7d2728a5e.png)

Here is the relevant XAML on the page that loads the FlowListView:
```
<flv:FlowListView HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" BackgroundColor="Black"
			        FlowItemsSource="{Binding Stations}" SeparatorVisibility="None" HasUnevenRows="false" RowHeight="150"
			        FlowItemTappedCommand="{Binding NavigateStationCommand}" FlowAutoColumnCount="true" FlowColumnDefaultMinimumWidth="125">
              <flv:FlowListView.FlowColumnsTemplates>
                <flv:FlowColumnSimpleTemplateSelector ViewType="{x:Type local:StationListView}"/>
              </flv:FlowListView.FlowColumnsTemplates>
            </flv:FlowListView>
```

And here is the ContentView XAML:

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentView xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="My.App.StationListView"
             HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand">
  <ContentView.Content>
    <Image Source="{Binding ImageUrl}" Aspect="Fill"></Image>
  </ContentView.Content>
</ContentView>
```

**Comment by TimeBomb006** [comment]
Please ignore.. My issue was that I was using the ListView inside a ScrollView.. it caused unwanted side effects. Your library is working perfectly fine. Thanks!

**Comment by daniel-luberda** [comment]
@TimeBomb006 Ok, thanks for the info! :)
