### ISSUE TITLE
Support for NetStandard???

### ISSUE THREAD

**Issue by nazgul87** [daniel-luberda/DLToolkit.Forms.Controls#120]
Hi Daniel, First of all I want to thank you about this great control, it has been very useful on my apps.
You'll see, I'm trying to migrate my PCL libraries to netStandard, but this control is not compatible with Net standard, so I want to ask you if you have in mind release a version compatible with that?

I'll really appreciate your comments. Thanks in advance.

**Comment by daniel-luberda** [comment]
I merged your PR, so we now have .NETStandard support. I'll release nuget containing fixes today :)

**Comment by nazgul87** [comment]
It's good to read that :) and know that I can help your awesome control library.

Thanks Daniel .
