### ISSUE TITLE
Code version without Xamvvm

### ISSUE THREAD

**Issue by Ruddy2007** [daniel-luberda/DLToolkit.Forms.Controls#122]
Hi,

I love the look of this plugin! Looks spot on, problem being I cannot get this to run at all. I just want a simple design (not using XAML or Xamvvm) but for some reason nothing ever is displayed. Do you have a super simple version using only code?

E.g why would this not work? (note: this in after i was messing around a bit. before there was a binding in the view cell etc)

            var testData = new FlowObservableCollection<SimpleItem>();
            for (int i = 0; i < 100; i++)
            {
                testData.Add(new SimpleItem() { Title = string.Format("Item nr {0}", i) });
            }

            var flowView = new FlowListView
            {
                VerticalOptions = LayoutOptions.FillAndExpand,
                HorizontalOptions = LayoutOptions.FillAndExpand,
                BackgroundColor = Color.Red,
                SeparatorVisibility = SeparatorVisibility.None,
                HasUnevenRows = false,
                FlowColumnCount = 3,
                FlowItemsSource = testData,
                FlowColumnTemplate = new DataTemplate(() =>
                {
                    var vc = new ViewCell();

                    Label la = new Label()
                    {
                        WidthRequest = 200,
                        HeightRequest = 200,
                        Text = "Just a test"
                    };

                    vc.View = la;
                    return vc;
                })
            };

            Content = flowView;

Note: I have been testing this on Android (Galaxy S8)

**Comment by Ruddy2007** [comment]
`public class ModelThing
    {
        public ModelThing()
        {
            DataStuff = new FlowObservableCollection<object>() { "Test", "Test", "Test", "Test", "Test", "Test", "Test" };
        }

        public FlowObservableCollection<object> DataStuff { get; set; }
    }
    public class Anothertest : ContentPage
    {
        public Anothertest()
        {
            this.BindingContext = new ModelThing();

            var flow = new FlowListView
            {
                BackgroundColor = Color.Red,
                FlowColumnCount = 3,
                FlowColumnTemplate = new DataTemplate(() =>
                {
                    var cell = new ViewCell();
                    var label = new Label
                    {
                        HorizontalOptions = LayoutOptions.Fill,
                        VerticalOptions = LayoutOptions.Fill,
                        BackgroundColor = Color.Blue,
                        Text = "Test"
                    };
                    cell.View = label;

                    return cell;
                })
            };
            flow.SetBinding(FlowListView.FlowItemsSourceProperty, new Binding("DataStuff", BindingMode.OneWay));

            Content = flow;
        }
    }`

I must not understand how this works because this now gives me the following error:

> [MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] System.InvalidCastException: Specified cast is not valid.
[MonoDroid]   at DLToolkit.Forms.Controls.FlowListViewInternalCell.UpdateData () [0x001b6] in <20224ac9235e4727adb45ad57ee52798>:0 
[MonoDroid]   at DLToolkit.Forms.Controls.FlowListViewInternalCell.OnBindingContextChanged () [0x00006] in <20224ac9235e4727adb45ad57ee52798>:0

**Comment by daniel-luberda** [comment]
You can't use `ViewCell` with `FlowListView`, replace `ViewCell` with `ContentView` or any other `View`.
