### ISSUE TITLE
Scrolling issue in iOS device for Advanced Grouping

### ISSUE THREAD

**Issue by solankivinay4u** [daniel-luberda/DLToolkit.Forms.Controls#123]
I am having issue of scrolling while using Grouping and lazy loading(Advance Grouping Example).  I checked sample in iPad and I found same issue.

**Comment by daniel-luberda** [comment]
Could you write more details?

**Comment by solankivinay4u** [comment]
Let's say, I have grouped list of 10 item initially. If scroll up and add new 10 items in the list, it does not scroll and show new items added. When I clicked on alphabet index at right side on iPad, it scrolls.

**Comment by daniel-luberda** [comment]
Is it possible to make a reproduction?
