### ISSUE TITLE
Example incomplete - No ItemSource setup code

### ISSUE THREAD

**Issue by AlmondMedia** [daniel-luberda/DLToolkit.Forms.Controls#124]
Please how do I setup the Item Source? 
Is it a normal list (e.g. an array of strings) or is it a more complex data source. I tried the earlier using the example on the readme page but it throws an error (`System.InvalidCastException`) when I run it.
Basically what is missing from the example is the Code behind file for the xaml that was shown.

I know this sounds basic and silly, but could any one help?

Thanks

**Comment by tdesmond-hunterindustries** [comment]
@daniel-luberda has stated before this is just an extension of list view so I am assuming just like list view any collection implementing IEnumerable should work just fine. 

I've made a quick sample app as well on my other account you can check it out here https://github.com/thetombomb91/FlowListViewSampleApp maybe it will help you with understanding. I'm just using ObservableCollection as my item source.

**Comment by daniel-luberda** [comment]
Thanks @tdesmond-hunterindustries 

 @AlmondMedia A common mistake is to use `ViewCell`, not a `View` (FlowListView doesn't support `ViewCells`

**Comment by daniel-luberda** [comment]
The newest nuget throws a more informative exception when eg `ViewCell` template is provided. Please reopen if you still have any problems.
