### ISSUE TITLE
FlowScrollTo bug

### ISSUE THREAD

**Issue by gr3chu** [daniel-luberda/DLToolkit.Forms.Controls#125]
Hi there,

First of all great work on your control - its awesome! 

Just wanted to let you know that I've found bug in your FlowScrollTo method in
DLToolkit.Forms.Controls/FlowListView/DLToolkit.Forms.Controls.FlowListView/FlowListView.cs

You are casting ItemsSoucre to IEnumerable:

var castedItemsSource = ItemsSource as IEnumerable<IEnumerable<object>>;
var internalItem = castedItemsSource?.FirstOrDefault(v => v.Contains(item));
ScrollTo(internalItem, position, animated);\

'As' in this case will always return null cause of the fact that ObservableCollection does not inherit  IEnumerable.

Hope this will be helpful. 
Again great job man :) 

Cheers!

**Comment by daniel-luberda** [comment]
Hi @gr3chu Thanks! Scrolling issues should be fixed with: https://github.com/daniel-luberda/DLToolkit.Forms.Controls/commit/167f34f98a8018e8eaf8e645186a7d806dbf399d

Cheers :)
