### ISSUE TITLE
Image HeightRequest does not do anything

### ISSUE THREAD

**Issue by mclintprojects** [daniel-luberda/DLToolkit.Forms.Controls#126]
Hi. I don't know if I'm doing anything wrong (I probably am) but I can't seem to set a height request for the image view I'm using as my columntemplate. In my xaml I set the height request to 96 but when I run the app, the height of the image is more like 48. Can you please help out?

Here's the xaml code 
```XML
<flow:FlowListView
      x:Name="mediaListView"
      HorizontalOptions="Fill"
      FlowColumnCount="3"
      SeparatorVisibility="None"
      HasUnevenRows="False"
      Margin="16,0,16,0"
	AbsoluteLayout.LayoutBounds="0,0,1,1"
	AbsoluteLayout.LayoutFlags="All">
      <flow:FlowListView.FlowColumnTemplate>
            <DataTemplate>
                  <Image
		      HorizontalOptions="Fill"
		      Source="{Binding Url}"
		      Aspect="AspectFill"
                      HeightRequest="96" />
            </DataTemplate>
      </flow:FlowListView.FlowColumnTemplate>
</flow:FlowListView>
```

**Comment by daniel-luberda** [comment]
It's because `HasUnevenRows`. If it's set to `false` you must also set `RowHeight` to some value. Just the same as with `Xamarin.Forms.ListView`.

**Comment by mclintprojects** [comment]
Thanks for the quick response. That fixed it. I'm new to Xamarin Forms so I'm still making these newbie mistakes 🤦.
