### ISSUE TITLE
Height of FlowListView.FlowColumnTemplate changes on scrolling / cell reusing

### ISSUE THREAD

**Issue by nor0x** [daniel-luberda/DLToolkit.Forms.Controls#127]
I have started with the grouping example and trying to implement grouping with different sizes for the `GroupHeaderTemplate` and the `FlowColumnTemplate` (which I want to be a square). I set `HasUnevenRows` to `true` and bound `HeighRequest` of the `Grid` which contains the all the cell elements to the `Width` property (which is calculated by `FlowListView` with `FlowColumnCount`). Unfortunately the binding seems to not work correctly, because the first time the list gets loaded the cells have a different row height, once scrolled / reused the height gets corrected.

Here is the XAML code of my `FlowListView`:
```
<flv:FlowListView x:Name="flowListView" FlowColumnCount="4" SeparatorVisibility="None"  FlowColumnExpand="None" HasUnevenRows="true" IsGroupingEnabled="true" FlowGroupDisplayBinding="{Binding Key}" FlowItemTappedCommand="{Binding ItemTappedCommand}" FlowLastTappedItem="{Binding LastTappedItem}" FlowItemsSource="{Binding Items}">
    <flv:FlowListView.GroupHeaderTemplate>
        <DataTemplate>
            <ViewCell>
                <Label Text="Header" VerticalOptions="Center" HorizontalOptions="Center" />
            </ViewCell>
        </DataTemplate>
    </flv:FlowListView.GroupHeaderTemplate>
    <flv:FlowListView.FlowColumnTemplate>
        <DataTemplate>
            <Grid>
                <Grid x:Name="ItemGrid" HeightRequest="{Binding Source={x:Reference ItemGrid}, Path=Width}" Margin="2" BackgroundColor="{Binding Color}">
                    <Label Grid.Row="1" Text="{Binding Title}"/>
                </Grid>
            </Grid>
        </DataTemplate>
    </flv:FlowListView.FlowColumnTemplate>
</flv:FlowListView>

```
I have recorded a GIF that shows the cells changing height on scrolling / reusing
![sep-06-2017-19-12-111](https://user-images.githubusercontent.com/3210391/30125432-af9c5fd6-9338-11e7-8056-3cba2cd41155.gif)

**Comment by daniel-luberda** [comment]
`HeightRequest="{Binding Source={x:Reference ItemGrid}, Path=Width}"` That would never work correctly. Layout cycle is a constant process and that value would be reapplied later tan you expect. 

Instead you could try something like: 

`HeightRequest="{Binding Source={x:Reference flowListView}, Path=Width}"`

**Comment by nor0x** [comment]
Thanks for the reply, I understand that. Can you think of any other way to ensure the cells are an exact square?

**Comment by daniel-luberda** [comment]
You can base on you screen width or `FlowListView.Width`, then divide it by number of columns
