### ISSUE TITLE
DLToolkit.Forms.Controls.FlowListView could not be resolved 

### ISSUE THREAD

**Issue by GregorioCunha007** [daniel-luberda/DLToolkit.Forms.Controls#128]
This is the error shown:

**The primary reference "DLToolkit.Forms.Controls.FlowListView, Version=1.0.6447.27582, Culture=neutral, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETPortable,Version=v5.0" framework. This is a higher version than the currently targeted framework ".NETPortable,Version=v4.5,Profile=Profile259".**		

This happened when I updated the flowlistview to the latest stable version. How can I change the targeted framework .NetPortable ? Thanks

**Comment by GregorioCunha007** [comment]
@daniel-luberda Do you have any idea how is this happening ? Only version 2.0.4 works, the other two next versions keep giving me this error

**Comment by thetombomb91** [comment]
Is your Xamarin.Forms package up to date?

**Comment by GregorioCunha007** [comment]
I tried with the pre-realeased version. Now I'm just with 2.3.3.193

**Comment by xmaux72** [comment]
Same here, working with 2.0.4, not working with following versions.
my error is, simply: "Failed to resolve assembly: 'DLToolkit.Forms.Controls.FlowListView, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'";

The error is at COMPILE time, not runtime. No linking issue.

XF: 2.4.0.282

The assembly is correctly into /packages.

**Comment by daniel-luberda** [comment]
Just call `FlowListView.Init()` or `var ignore = typeof(FlowListView)` somewhere in your code. Xamarin  linker removes it.

**Comment by daniel-luberda** [comment]
If it's while building, make sure you added nuget package.
