### ISSUE TITLE
TagEntryView width issue

### ISSUE THREAD

**Issue by trqvinh90** [daniel-luberda/DLToolkit.Forms.Controls#129]
I have a **Stacklayout** with **horizontal** orientation
I have some control inside and the TagEntryView take the rest ( HorizontalOptions="FillAndExpand" )
Unhappily, the tag view doesn't work as expected : It take a lot of width in the stack

Ex :
                  `<StackLayout HorizontalOptions="FillAndExpand" Orientation="Horizontal">
                        <Label                          
                            Text="ABC:"
                            WidthRequest="100" />
                        <dltag:TagEntryView HorizontalOptions="FillAndExpand">
                            <dltag:TagEntryView.TagItemTemplate>
                                <DataTemplate>
                                    ...
                                </DataTemplate>
                            </dltag:TagEntryView.TagItemTemplate>
                        </dltag:TagEntryView>
                    </StackLayout>`

**Comment by daniel-luberda** [comment]
@trqvinh90 Could you write more details? I'm not quite sure if I understand what's the problem?
