### ISSUE TITLE
Unable to read package: File contains corrupted data

### ISSUE THREAD

**Issue by 3-50** [daniel-luberda/DLToolkit.Forms.Controls#13]
Hi!
After installing DLToolkit.Forms.Controls.FlowListView, I can no longer install/update any other package. I get this error in the package manager console:
Unable to read package from path "DLToolkit.Forms.Controls.FlowListView.1.0.7\DLToolkit.Forms.Controls.FlowListView.1.0.7.nupkg". File contains corrupted data.

I am using VS2015 14.0.2542400.00 Update 3.

**Comment by daniel-luberda** [comment]
It's not DLToolkit.Forms.Controls.FlowListView package issue. 

Your Visual Studio nuget cache is corrupted. You need to:
- clean it
- remove all packages
- remove `packages` folder from your project.

**Comment by 3-50** [comment]
Are you sure?
i 'am trying to delete folder "packages" from project.. It did not help.
Just now:
New project -> add, for example, Xamarin.FFImageLoading -> work fine!
New project -> add DLToolkit.Forms.Controls -> "File contains corrupted data"

Same problem
https://github.com/moment/moment/issues/3285

**Comment by daniel-luberda** [comment]
Yes, I'm sure. Your Visual Studio installation nuget package cache for DLToolkit.Forms.Controls is corrupted. Please google how to clean it.

**Comment by 3-50** [comment]
i'am so sorry, but these commands
nuget.exe locals -clear all 
nuget.exe locals -clear http-cache 
nuget.exe locals -clear packages-cache 
nuget.exe locals -clear global-packages
nuget.exe locals -clear temp
useless too...

i can record my screen....

**Comment by daniel-luberda** [comment]
- `del %LOCALAPPDATA%\NuGet\Cache\*.nupkg /q`
- `nuget locals all -clear`
- `dnu clear-http-cache`
- `dotnet restore --no-cache`

**Comment by 3-50** [comment]
It didn't work out. 

Solution.
1) Unpack zip archive (rename "DLToolkit.Forms.Controls.FlowListView.1.0.7.nupkg" to "DLToolkit.Forms.Controls.FlowListView.1.0.7.zip") 
2) edit files: "DLToolkit.Forms.Controls.FlowListView.nuspec", "d17c440ccd5f498e8fe7b8b7e3739740.psmdcp"
from <version>1.0.7</version>
to <version>1.0.6</version>
3) Packs the files/folders to a zip archive and rename .zip to .nupkg

**Comment by 3-50** [comment]
Hello again!
I do clean install Windows 10 v1607 on another partition, I installed VS2015.
New project -> add DLToolkit.Forms.Controls -> "File contains corrupted data".

> It's not DLToolkit.Forms.Controls.FlowListView package issue.
O rly?

**Comment by wagnerps** [comment]
Hello, i'm having the same issue, every time i need to update / install another package, i need to uninstall FlowListView, install/update other packages and then reinstall FlowListView.

**Comment by 3-50** [comment]
Are you trying edit files "DLToolkit.Forms.Controls.FlowListView.nuspec", "d17c440ccd5f498e8fe7b8b7e3739740.psmdcp"?

**Comment by wagnerps** [comment]
My problem is a little different:

Severity	Code	Description	Project	File	Line	Suppression State
Error		An error occurred while retrieving package metadata for 'DLToolkit.Forms.Controls.FlowListView.1.0.7' from source 'D:\path\project\packages'.			0
