### ISSUE TITLE
command is not firing for the control inside DataTemplate

### ISSUE THREAD

**Issue by Thavudu** [daniel-luberda/DLToolkit.Forms.Controls#131]
I am using Templateseletor and selecting contentview based on list's object property state. Inside my contentview template I have an image with Tapgeasture. When I click on the image command is not firing. Is it possible to fire a command from the cell?

**Comment by Thavudu** [comment]
**Main Page XAML**
<flv:FlowListView x:Name="flowlstview" FlowColumnCount="4" FlowColumnExpand="None"  SeparatorColor="Orange" HasUnevenRows="True"
                                        FlowItemsSource="{Binding lstAddress}"  >
                                        <flv:FlowListView.FlowColumnTemplate>
                                            <TemplateSelector:EditTemplateSelector/>
                                        </flv:FlowListView.FlowColumnTemplate>
                                    </flv:FlowListView>
**ContentView Template**
<ContentView.Content>
	<StackLayout Spacing="1" VerticalOptions="FillAndExpand">
                    <Image Source="Home_Button_Float.png"/>
                    <Image Source="Tick_Orange.png">
                        <Image.GestureRecognizers>
                            <TapGestureRecognizer Command="{Binding HandleEditAddress}" 				CommandParameter="{Binding .}" />
                        </Image.GestureRecognizers>
                    </Image>
                </StackLayout>
                <StackLayout Grid.Column="1">
                    <Label Text="Home Address"/>
                    <Label Text="{Binding address1}"/>
                    <Label Text="{Binding Address2}"/>
                    <Label Text="{Binding State}"/>
                    <Label Text="{Binding City}"/>
                    <Label Text="{Binding Pincode}"/>
                </StackLayout>
            </Grid>
        </StackLayout>
</ContentView.Content>

after the screen is populated **HandleEditAddress** command is not firing.
Is't doable with FlowListView Control?

**Comment by daniel-luberda** [comment]
@Thavudu `GestureRecognizers` work just fine, you'll need to provide some code or sample project. Does your view model have `HandleEditAddress` property? What it looks like? Does your view model implement `INotifyPropertyChanged`?

**Comment by Thavudu** [comment]
@daniel-luberda  Below is my viewModel
public class PatientProfileViewModel : INotifyPropertyChanged
{
public event PropertyChangedEventHandler PropertyChanged;
public Command<DeliveryAddressModel> EditAddressCommand { get; set; }
public PatientProfileViewModel()
{
EditAddressCommand = new Command<DeliveryAddressModel>((DeliveryAddressModel arg)=> HandleEditAddress(arg) );
}

private void HandleEditAddress(DeliveryAddressModel arg)
        {
//logic code here

}
public virtual void OnPropertyChanged(string propertyName)
{
if (PropertyChanged == null)
return;
PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
}
}

HandleEditAddress command is getting fired from outside FlowListview. But its not happening for the items inside the Flowlistview content. 
Am I missing anything here?

**Comment by daniel-luberda** [comment]
Yes, items should have own view models and that `Command` should be inside item view model, not your main view model.

**Comment by Thavudu** [comment]
@daniel-luberda  Thank you. But I have my logic here in my MainViewModel, Is there any possible way to call the handler in main view model?

**Comment by daniel-luberda** [comment]
For example: You can pass `ICommand` instance to your item view model constructor.

**Comment by Thavudu** [comment]
Not able to get you. Can you elaborate little please?

**Comment by Thavudu** [comment]
I have added the command in Item view model and its hitting. Based on that I have changed the selected object state. But how would I notify my main view model that item view model state got changed. Because I have ObservableCollection of my item view model object in Main View Model. So I need to notify my Main view model about the item view model object state change. Could you please help me out?

**Comment by daniel-luberda** [comment]
You can implement that Command in your page model and then pass it to items models in constructor. Did you try it?

**Comment by rajeshkumarmanickam** [comment]
Awesome! I have assigned the  main view model's Command to item view model's command, its working fine.
Sorry for late reply
