### ISSUE TITLE
FlowColumnTemplate not binding code working in xaml

### ISSUE THREAD

**Issue by prasannamca1107** [daniel-luberda/DLToolkit.Forms.Controls#133]
here i done code:

                                testlistview = new List<tagname>();
				testlistview.Add(new tagname { Name = "xamarin1" });
				testlistview.Add(new tagname { Name = "xamarin2" });
				testlistview.Add(new tagname { Name = "xamarin3" });
				testlistview.Add(new tagname { Name = "xamarin4" });

			      myList = new FlowListView()
				{
				 FlowColumnCount = 2,
				 SeparatorVisibility = SeparatorVisibility.None,
				 HasUnevenRows = false,
				 BackgroundColor = Color.White
				                        
				};

			var personDataTemplate = new DataTemplate(() =>
			{
				var grid = new StackLayout();
				var nameLabel = new Label { FontAttributes = FontAttributes.Bold, TextColor = Color.Black };
				nameLabel.SetBinding(Label.TextProperty, new Binding("Name"));
				grid.Children.Add(nameLabel);
				return new ViewCell { View = grid };
			});
			myList.FlowUseAbsoluteLayoutInternally = true;
			myList.FlowColumnCount = 5;
			myList.FlowRowBackgroundColor = Color.Green;
			myList.FlowColumnExpand = FlowColumnExpand.Proportional;
			myList.FlowItemsSource =testlistview;
			myList.FlowColumnTemplate =personDataTemplate;
			myList.ItemTapped += FlowListView_OnFlowItemTapped;

correct me plz

**Comment by daniel-luberda** [comment]
What's the question? Examples are on our repo. 

You should set  `myList.FlowColumnTemplate` before `myList.FlowItemsSource`
