### ISSUE TITLE
IsGroupingEnabled can cause possible Null argument exception when setting source to null

### ISSUE THREAD

**Issue by ShiroYacha** [daniel-luberda/DLToolkit.Forms.Controls#134]
Hello,

In line 627 of FlowListView.cs, there is a cast on the IEnumerable FlowItemsSource when IsGroupingEnabled is true. This can cause a null argument exception if the FlowItemsSource is set to null (previously not null). This happens when my view is destroyed (VM is set to null)... or when I just want to set it to null or something that is not INotifyCollectionChanged.

I am using Prism and when I set the IsGroupingEnabled = false when the view is destroyed the error goes away... IMO, the cast should probably be: `var groupedSource = FlowItemsSource?.Cast<INotifyCollectionChanged>();`?

Can you verify if this is indeed a bug or I am missing something?

Thanks!

**Comment by daniel-luberda** [comment]
Yes, it's a bug. Nice catch. Fixed :)
