### ISSUE TITLE
Group Header bindings not updating on property changes

### ISSUE THREAD

**Issue by richardpike** [daniel-luberda/DLToolkit.Forms.Controls#135]
Hello,

If I update my ObservableRangeCollection, then the items (or column templates) get updated but the group headers remain the same. Here's my XAML:

```
<flv:FlowListView FlowItemsSource="{Binding PlayersListSimsGrouped}"
			   x:Name="PlayerListView"
			   FlowGroupDisplayBinding="{Binding Key}"
			   GroupDisplayBinding="{Binding Key}"
			   IsGroupingEnabled="True"
			   AbsoluteLayout.LayoutFlags="All"
			   AbsoluteLayout.LayoutBounds="0,0,1,1"
			   SeparatorVisibility="None"
			   FlowItemTapped="PlayerListView_FlowItemTapped"
			   HasUnevenRows="True"
			   FlowColumnExpand="Proportional">
	<flv:FlowListView.GroupHeaderTemplate>
		<DataTemplate>
			<ViewCell>
				<StackLayout BackgroundColor="{Binding Key.BackgroundColor}">
					<StackLayout.GestureRecognizers>
						<TapGestureRecognizer Tapped="TapGestureRecognizer_Tapped"/>
					</StackLayout.GestureRecognizers>
					<StackLayout Orientation="Horizontal"
							      HorizontalOptions="CenterAndExpand">
						<Label Text="{Binding Key.PlayerLabel}"
							    HorizontalOptions="Center"/>
						<Label Text="{Binding Key.TeamName}"
							    HorizontalOptions="Center"/>
					</StackLayout>
					<Image Source="{localHelpers:ImageResource MyNamespace.Images.image.png}"
						      HeightRequest="100"
						      WidthRequest="100"/>
				</StackLayout>
			</ViewCell>
		</DataTemplate>
	</flv:FlowListView.GroupHeaderTemplate>
	<flv:FlowListView.FlowColumnTemplate>
		<DataTemplate>
			<Label Text="{Binding EquipmentType}"
				    BackgroundColor="{Binding SimBackgroundColor}"
				    HorizontalOptions="Fill"
				    VerticalOptions="Fill"
				    XAlign="Center"
				    YAlign="Center"/>
		</DataTemplate>
	</flv:FlowListView.FlowColumnTemplate>
</flv:FlowListView>
```

When I change my collection, I'm (sometimes) reordering the groups. But when I update to make group 2 appear first, what appears to happen in the list is the columns that belong to item 1 show up in group 2, and the items for group 2 show under to group 1. Breaking on the collection shows me the data how I expect it.
The binding works as expected when I use Xamarins standard ListView with groupings, the list gets updated.

Any thoughts on forcing an the bindings to update? I tried calling ProcPropertyChanged on each key element after updating but no joy.

**Comment by daniel-luberda** [comment]
Could you make a simple repo, so I could fix this?

**Comment by richardpike** [comment]
Hi,
I've created a repo here:
[https://github.com/richardpike/FlowListViewExample](https://github.com/richardpike/FlowListViewExample)

It's the template master detail project with a load stripped out, then adding in an FLV under the standard list view. I've added in a couple of buttons which change the order of the list
Hope this helps.

**Comment by daniel-luberda** [comment]
It's fixed. You can test it in 2.0.8
