### ISSUE TITLE
A little long press does not trigger ItemTapped command

### ISSUE THREAD

**Issue by marufbd** [daniel-luberda/DLToolkit.Forms.Controls#136]
Not sure why that behaviour? I need to be very quick like a mouse click always works, but when in device tap with finger is slow so does not work, on emulator if I mouse click and hold for half a sec then also does not trigger tap command.
I am setting properties like this:
```
SeparatorVisibility="Default" HasUnevenRows="True"                                
                               IsGroupingEnabled="True"
                               FlowGroupColumnCountBinding="{Binding ColumnCount}"
                               FlowTappedBackgroundColor="Accent"
                               FlowTappedBackgroundDelay="300"
                               FlowItemTappedCommand="{Binding ItemSelectedCommand}"
                               SeparatorColor="DimGray"
                               FlowItemsSource="{Binding Items}"
```

**Comment by daniel-luberda** [comment]
`FlowItemTappedCommand` is implemented with `TapGestureRecognizer` which is a part of Xamarin.Forms. I don't think we can do anything to change its behaviour.

**Comment by marufbd** [comment]
I think the tap gesture is fine in the samples but for some reason in my implementation this is behaving differently, I am scratching my head at the moment to figure it out, will let you know, thanks.

**Comment by marufbd** [comment]
[TestApp.zip](https://github.com/daniel-luberda/DLToolkit.Forms.Controls/files/1389954/TestApp.zip)
@daniel-luberda I have created the simplest example here, still could not figure out why long press here does not work, but in your example it works, I am just using .net standard instead of PCL project

**Comment by daniel-luberda** [comment]
Maybe it's because missing renderers as described here: https://github.com/daniel-luberda/DLToolkit.Forms.Controls/tree/master/FlowListView#faq

Did you try it?

**Comment by daniel-luberda** [comment]
I'll close this as: 

- issue is quite old
- it's probably a XF issue which could be fixed now (FlowListView is a ListView)

Please reopen if you have a repo. Thanks.
