### ISSUE TITLE
How to use android selector on pressed change item background color

### ISSUE THREAD

**Issue by marufbd** [daniel-luberda/DLToolkit.Forms.Controls#137]
I am trying to  change item background color on press, not when released.

I have previously got that behaviour by using in my android project drawable/catalog_item_selector:
```
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
  <item android:state_pressed="true" android:drawable="@color/brand_yellow"/>  
  <item android:drawable="@color/itemBackground"/>  
</selector>
```
I have used this with a recyclerview and adapter where each item is rendered as a relative layout with background set as 
`android:background="@drawable/catalog_item_selector"`

The effect I get is when pressed the background is highlighted.

In order to achieve the same with FlowListView I am trying to use native renderer which does not work:

```
[assembly: ExportRenderer(typeof(FlowListViewInternalCell), typeof(FlowListViewInternalCellRenderer))]
namespace Ui.Droid.XamForms.Renderers
{
    public class FlowListViewInternalCellRenderer : ViewCellRenderer
    {
        protected override Android.Views.View GetCellCore(Cell item, Android.Views.View convertView,
            Android.Views.ViewGroup parent, Android.Content.Context context)
        {
            var cell = base.GetCellCore(item, convertView, parent, context);

            cell.SetBackgroundResource(Resource.Drawable.catalog_item_selector);

            var listView = parent as Android.Widget.ListView;
            if (listView != null)
            {
                //listView.SetSelector(Resource.Drawable.catalog_item_selector);
                listView.CacheColorHint = Android.Graphics.Color.Transparent;
            }

            return cell;
        }
    }
}
```

I am not setting any background color on any item template each cell can take background from the native renderer, nut still it does not change background on pressed.

Is there any other way to achieve item background change on press.

**Comment by daniel-luberda** [comment]
You can use somthing like this: http://www.mrgestures.com
Or implement a custom View (which will be your cells root view) and implement tap gestures via custom renderers.
