### ISSUE TITLE
Crash in 2.0.9

### ISSUE THREAD

**Issue by ozzy1873** [daniel-luberda/DLToolkit.Forms.Controls#139]
I am experiencing a crash when using 2.0.9. Reverting to 2.0.7, there is no crash.

> 
            <flv:FlowListView SeparatorVisibility="None" 
                              HasUnevenRows="True"
                              FlowItemAppearingCommand="{Binding PhotoItemAppearingCommand}"
                              FlowColumnMinWidth="100"  
                              FlowItemsSource="{Binding UserPhotos}"
                              FlowItemTappedCommand="{Binding PhotoTappedCommand}">
                <flv:FlowListView.FlowColumnTemplate>
                    <DataTemplate>
                        <Grid>
                            <Grid.RowDefinitions>
                                <RowDefinition Height="*"/>
                                <RowDefinition Height="Auto" />
                            </Grid.RowDefinitions>

                            <Grid.ColumnDefinitions>
                                <ColumnDefinition Width="*" />
                            </Grid.ColumnDefinitions>

                            <ff:CachedImage HeightRequest="100" 
                                            Aspect="AspectFit"
                                            DownsampleHeight="100" 
                                            DownsampleUseDipUnits="False" 
                                            LoadingPlaceholder="image_wait.png" 
                                            ErrorPlaceholder="image_error.png"
                                            Source="{Binding ThumbUrl}"/>
                        </Grid>
                    </DataTemplate>
                </flv:FlowListView.FlowColumnTemplate>
            </flv:FlowListView>

**Comment by chrisfoulds** [comment]
same

**Comment by thimmy687** [comment]
I guess it is related to #140 (still open in my eyes)

**Comment by daniel-luberda** [comment]
I just released 2.0.10 which includes the fix. Please reopen if you still experience it. Thanks.

**Comment by ozzy1873** [comment]
Looks like it is fixed. Thanks!

Sent from Mail for Windows 10
