### ISSUE TITLE
Request: Add pagination

### ISSUE THREAD

**Issue by khaledsawwaf** [daniel-luberda/DLToolkit.Forms.Controls#14]
Hello,
is it available to add pagination functionality to your supported list instead of scrolling down please?

**Comment by opcodewriter** [comment]
I don't think this should be the responsibility of the `FlowListView` control.
It's up to the items source to define the pages of data, this control just renders the items given by the items source.

**Comment by daniel-luberda** [comment]
Yes, pagination should be implemented independently of FlowListView (You can use `FlowItemAppearing/Disappearing` event for that). This control should work similar to Xamarin.Forms `ListView`, only with column support.
