### ISSUE TITLE
OnChildAdded not called when Item added to FlowItemsSource

### ISSUE THREAD

**Issue by XamDevv** [daniel-luberda/DLToolkit.Forms.Controls#141]
Why is OnChildAdded not called when an Item is added to FlowItemsSource?

**Comment by daniel-luberda** [comment]
What do you mean? There's no `OnChildAdded` property in FlowListView

**Comment by XamDevv** [comment]
You're right. It belongs to the base class Xamarin.Forms.Element.

What we want to achieve is to be notified when an element is added to or removed from the FLV. Then we want to get the corresponding VisualElement and call a Method of it. We need this as the FLV children have to dynamically adjust their FontSize based on the Element Height. When the window size is changed, we update FLV.FlowColumnMinWidth and FLV.RowHeight in a control derived from FLV. The children should then adjust their FontSize when Height PropertyChanged. This works just fine most of the time. But when an element is added to or removed from the FLV.FlowItemsSource, they get a Height different from what is shown. The Height is smaller than the actual drawn Height and so the FontSize ends up being too small. So the idea is to call FLVChild.AdjustFontSize() on all children as soon as the FlowItemsSource has changed.

How can we achieve that?

**Comment by XamDevv** [comment]
Maybe I explained too detailed. Lets try again: How to access the FLV children control instances when an item is removed or added to FlowItemsSource?

**Comment by daniel-luberda** [comment]
The key is to put this in your custom view class:

```C#
        protected override void OnBindingContextChanged()
        {
            base.OnBindingContextChanged();
            //TODO call method here
        }
```

**Comment by XamDevv** [comment]
I don't think this helps us. Here are the relevant parts of our Code:

`public class ScalableFlowListView : FlowListView
    {
        private const double ItemAspectRatio = 1.0;

        protected override void OnPropertyChanged(string propertyName = null)
        {
            base.OnPropertyChanged(propertyName);

            if (propertyName == nameof(Width) ||
                propertyName == nameof(Height))
            {
                AdjustItemAspectRatio();
            }
        }

        private void AdjustItemAspectRatio()
        {
            FlowColumnMinWidth = Width / 20;
            RowHeight = (int)(FlowColumnMinWidth / ItemAspectRatio) + (int)(1250 / Width);
        }
    }`

In this class derived from FlowListView we adjust the FlowColumnMinWidth and RowHeight to resize the FlowItems.


`public class ComponentControl : ContentView
    {

...

        private double _lastWidth, _lastHeight;

        protected override void OnSizeAllocated(double width, double height)
        {
            base.OnSizeAllocated(width, height);

            if (Math.Abs(width - _lastWidth) > double.Epsilon && Math.Abs(height - _lastHeight) > double.Epsilon)
            {
                AdjustFontSize();

                _lastWidth = width;
                _lastHeight = height;
            }
        }

        private void AdjustFontSize()
        {
            if (string.IsNullOrEmpty(Text)) return;

            Debug.WriteLine(nameof(Height) + ": " + Height);
            var fontSize = Height * 0.3;

            if (Math.Abs(_label.FontSize - fontSize) > double.Epsilon)
            {
                _label.FontSize = fontSize;
            }
        }

...

`

This is the class of the FlowItems. If Width and Height has changed, we set the Label.FontSize according to the Height. This works fine when we resize the FlowListView. But when we add or remove an element from the FlowItemsSource, all Items get a wrong Height in AdjustFontSize() and so the FontSize is wrong. The wrong size is 40, whereas the actual size is 55 (displayed size).
