### ISSUE TITLE
ListView doesn't scroll to the end when I back to page with list view

### ISSUE THREAD

**Issue by dimonkomaron** [daniel-luberda/DLToolkit.Forms.Controls#143]
Hello. I have FlowListView shown on first attach.

<img width="256" alt="screenshot at nov 20 12-36-19" src="https://user-images.githubusercontent.com/3322540/33011585-78f3574a-cdef-11e7-9f8d-51c589c55750.png">

And problem is that when I navigate to next page and return back listview doesn't scrolls to end. (See attach)

<img width="267" alt="screenshot at nov 20 12-35-05" src="https://user-images.githubusercontent.com/3322540/33011643-a5d1d2fa-cdef-11e7-9d71-6eee796a9a39.png">

**Comment by dimonkomaron** [comment]
Also I want each row to be on it's own section and create tiles menu(Row can contain several items, for example big on the left, and two items on the right). But I don't find a way to remove grouping header. How to make it invisible?

**Comment by dimonkomaron** [comment]
And another my question Am I have an ability to use row span for create list view as shown on attach?

![392x696bb](https://user-images.githubusercontent.com/3322540/33011747-ec75f1a0-cdef-11e7-87a6-331b060474bb.jpg)

**Comment by daniel-luberda** [comment]
I'll close this as: 

- issue is quite old
- it's probably a XF issue which could be fixed now (FlowListView is a ListView. 

Please reopen if you have a repo. Thanks.
