### ISSUE TITLE
Nuget download issue on PCL project

### ISSUE THREAD

**Issue by softsan** [daniel-luberda/DLToolkit.Forms.Controls#149]
Hi,

Tried to download and install DLToolkit
https://www.nuget.org/packages/DLToolkit.Forms.Controls.ImageCropView

`Could not install package 'System.Runtime.InteropServices.RuntimeInformation 4.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`
 
i already tried the workaround shown here:
https://forums.xamarin.com/discussion/80045/error-using-nuget

but then all my other dependencies not loaded.

**Comment by daniel-luberda** [comment]
Yes, it's because RX dependencies. I'll try to remove that dependency but I'll need to think of how to handle event throttling without it first.

**Comment by daniel-luberda** [comment]
I just removed RX dependencies, just use 1.0.5 nuget :) It should work now on 111 profile.
