### ISSUE TITLE
FlowColumnTemplate with 1 FlowColumnCount

### ISSUE THREAD

**Issue by LuisM000** [daniel-luberda/DLToolkit.Forms.Controls#150]
Hi,

I have a problem with FlowColumnTemplate. In the example ["Template selector example" ](https://github.com/daniel-luberda/DLToolkit.Forms.Controls/tree/master/Samples/DLToolkitControlsSamples/SamplesFlowListView), if I set FlowColumnCount = "1" and the FlowTeamplateSelector is:
```
public class TemplateSelectorPageSelector : FlowTemplateSelector
	{
		// Reuse DataTemplates instances !!!
		readonly DataTemplate _leftTemplate = new DataTemplate(typeof(TemplateSelectorPageTemplateLeft));
		readonly DataTemplate _rightTemplate = new DataTemplate(typeof(TemplateSelectorPageTemplateRight));
		protected override DataTemplate OnSelectTemplate(object item, int columnIndex, BindableObject container)
		{
            SimpleItem simpleItem = item as SimpleItem;
            if (simpleItem.Id % 2 == 0)
            {
                return _leftTemplate;
            }

            return _rightTemplate;
		}
	}
```
When I go up and scroll down, the template is messy ([https://imgur.com/a/8walH](https://imgur.com/a/8walH)).
Am I doing something wrong?

Thanks.
Regards,

Luis

**Comment by daniel-luberda** [comment]
Fixed :)

**Comment by LuisM000** [comment]
Thanks!!
