### ISSUE TITLE
Flowlistview crashes if observablecollection bound to it, is cleared.

### ISSUE THREAD

**Issue by sanmanborate** [daniel-luberda/DLToolkit.Forms.Controls#151]
Steps to produce 
1.Bind an observable collection
2.Add objects/items to collection, carousel loads successfully
3.Start removing one by one.
4.When you remove last element from the collection, app crashes with sequence has no elements exceptions.

**Comment by daniel-luberda** [comment]
Are you sure you use the newest package version? That bug was already fixed.
