### ISSUE TITLE
ImageCropView - Can not reset Image Source

### ISSUE THREAD

**Issue by robinmanuelthiel** [daniel-luberda/DLToolkit.Forms.Controls#153]
I was expecting, that the `ImageCropView` resets (deletes the currently displayed image) when its `Source` property is set to `null`.

```csharp
MyImageCropView.Source = null; // nothing happens
```

Instead, nothing happens and the last image source is still visible.

**Comment by daniel-luberda** [comment]
Nice catch, will fix it now :)

**Comment by robinmanuelthiel** [comment]
Great, thanks a lot!

**Comment by robinmanuelthiel** [comment]
Which version will it be part of?

**Comment by daniel-luberda** [comment]
Newest nuget
