### ISSUE TITLE
FlowListView not show the data in Xamarin.Forms

### ISSUE THREAD

**Issue by ludiaz** [daniel-luberda/DLToolkit.Forms.Controls#154]
Hi,

I'm trying use the example SimpleGalleryPage of [Samples]( https://github.com/daniel-luberda/DLToolkit.Forms.Controls/tree/master/Samples/DLToolkitControlsSamples/SamplesFlowListView) and i don't know that is happening.

When i use the FlowListView, like [here](https://github.com/daniel-luberda/DLToolkit.Forms.Controls/blob/master/Samples/DLToolkitControlsSamples/SamplesFlowListView/SimpleGalleryPage.xaml) and not show for me. If i switch Flowlistview to Listview, the info is showed. 

The xaml is the same of example. Here is the C# code:

`    [XamlCompilation(XamlCompilationOptions.Compile)]
    public partial class Cameras : global::Xamarin.Forms.ContentPage
    {
        protected FlowObservableCollection<MyDataClass> ItemsFlow = null;

        public Cameras()
        {
            InitializeComponent();

            GetCameras();
        }

        private async void GetCameras()
        {
		Webservice webservice = RestService.For<Webservice>(Http.Get());

                Requests.MyDataClass dataClass= await webservice.DataClass();

                if (dataClass.Status)
                {
                    this.ItemsFlow = dataClass.ItemsFlow;
                    FlowListViewCameras.ItemsSource = this.ItemsFlow;
                }

        }

    }`

How i say, with list view the data is showed, but using flowlistview nothing appears. 

Thanks for the help!

**Comment by daniel-luberda** [comment]
Change this: 

```C#
FlowListViewCameras.ItemsSource = this.ItemsFlow;
```

to this

```C#
FlowListViewCameras.FlowItemsSource = this.ItemsFlow;
```
