### ISSUE TITLE
FlowItemTappedCommand does not work on macOS

### ISSUE THREAD

**Issue by YZahringer** [daniel-luberda/DLToolkit.Forms.Controls#156]
The FlowItemTappedCommand command is not called on macOS. The same XAML works on other platforms.

**Comment by daniel-luberda** [comment]
Should be fixed now :)

**Comment by YZahringer** [comment]
Have you planned to release a new version with the fix? or pre-release?

**Comment by YZahringer** [comment]
Tried with the fix, still not working
