### ISSUE TITLE
Placing Flow Listview in first Tab of a TabbedPage

### ISSUE THREAD

**Issue by johnkennethfurog** [daniel-luberda/DLToolkit.Forms.Controls#157]
FlowListview is not rendering it's FlowItemsource when placed on the first tab of a TabbedPage.

Android Version : Marsmallow

**Comment by daniel-luberda** [comment]
I'll close this as: 

- issue is quite old
- it's probably a XF issue which could be fixed now. 

Please reopen if you have a repo. Thanks.
