### ISSUE TITLE
Image is visible only while panning or pinching

### ISSUE THREAD

**Issue by thearaks** [daniel-luberda/DLToolkit.Forms.Controls#158]
I'm testing ImageCropView and having an issue on both Android and iOS.
The image is visible only while panning or pinching:
![simulator screen shot - iphone 8 - 2017-12-22 at 16 29 25](https://user-images.githubusercontent.com/5188791/34303907-d0ceae4a-e737-11e7-8360-09bc8877c8cf.png)

When the gesture ends the image disappears:
![simulator screen shot - iphone 8 - 2017-12-22 at 16 29 29](https://user-images.githubusercontent.com/5188791/34303918-dce70574-e737-11e7-983e-0ea948d783b4.png)

I'm using:
- Xamarin.Forms 2.5.0.121934
- Xamarin.FFImageLoading 2.3.1
- DLToolkit.Forms.Control.ImageCropView 1.0.6

Thank you!

**Comment by thearaks** [comment]
Solved, changed image loading from:
```
cropView.Source = ImageSource.FromStream(() =>
            {
                var stream = mediaFile.GetStream();
                mediaFile.Dispose();
                return stream;
            });
```

To:
```
cropView.Source = ImageSource.FromStream(() =>
            {
                return mediaFile.GetStream();
            });
```

**Comment by napalm684** [comment]
I am seeing this problem still as well with the load as you describe as the fix.

**Comment by napalm684** [comment]
More data...it appears it is not liking getting the stream from the iOS image picker as a stream and passing it over as an imagesource to the cropView....Works fine if set the source as a string path :-/
