### ISSUE TITLE
Question : Cell Height Auto iOS

### ISSUE THREAD

**Issue by lwinged** [daniel-luberda/DLToolkit.Forms.Controls#16]
For example : 
In my cell I have a short text and after tapped on it the text comes longer.

Result : the text overlaps the next cell on iOS. 

Is it possible to manage cell height automatically with the FlowListView?

**Comment by lwinged** [comment]
I don't understand why HasUnevenRows="true" doesn't work.
The text overlaps other cells.

I use : 

<flv:FlowListView x:Name="flView" SeparatorVisibility="None" HasUnevenRows="true"></flv:FlowListView>

and in my Testview

<ContentView.Content>
		<StackLayout Spacing="10" x:Name="contentStack" BackgroundColor="{StaticResource whiteColor}">
			

			<Label x:Name="description" Text="{Binding LongContext}" FontFamily="Roboto-Regular" FontSize="15" /> 

	</StackLayout>
	</ContentView.Content>
</ContentView>

Thank you for your help.

**Comment by daniel-luberda** [comment]
You just need to set correct `HorizontalOptions` and `VerticalOptions` layout flags on a main cell view. Duplicate issue here: https://github.com/daniel-luberda/DLToolkit.Forms.Controls/issues/17
