### ISSUE TITLE
Custom renderer not always called by FlowListView

### ISSUE THREAD

**Issue by hugoterelle** [daniel-luberda/DLToolkit.Forms.Controls#163]
I have a solution written in Xamarin.Forms targetting mainly UWP (for the moment). I wrote a custome renderer to center and word-wrap text in all button of the solution:

```
[assembly: ExportRenderer(typeof(Button), typeof(CustomButtonRenderer))]
namespace PosExclusive.Renderers
{
  public class CustomButtonRenderer : ButtonRenderer
  {
    protected override void OnElementChanged(ElementChangedEventArgs<Button> e)
    {
        base.OnElementChanged(e);

        if (Control?.Content is string text)
        {
            var textBlock = new TextBlock
            {
                Text = text,
                VerticalAlignment = VerticalAlignment.Center,
                HorizontalAlignment = HorizontalAlignment.Center,
                TextAlignment = TextAlignment.Center,
                TextWrapping = TextWrapping.WrapWholeWords
            };
            Control.Content = textBlock;
        }
    }
  }
}
```
I included the DLToolkit.Forms.Controls.FlowListView with the following XAML:

```
<controls1:FlowListView Grid.Column="1" Grid.Row="0"
    SeparatorVisibility="None" HasUnevenRows="False"
    FlowColumnMinWidth="100" FlowItemsSource="{Binding Items}">
    <controls1:FlowListView.FlowColumnTemplate>
        <DataTemplate>
            <Button HeightRequest="80" BackgroundColor="DeepSkyBlue" 
                Text="{Binding Label}" FontSize="12"
                Command="{Binding Path=BindingContext.PushItemCommand, Source={x:Reference Name=SalesPage}}"
                CommandParameter="{Binding .}" />
        </DataTemplate>
    </controls1:FlowListView.FlowColumnTemplate>
</controls1:FlowListView>
```
But the result is strange because my custom renderer is not always called by the flowlistview.  
I tried using a standard listview (without columns) and it's working fine.

![image](https://user-images.githubusercontent.com/2490657/34776690-00f80c9e-f618-11e7-961a-fb937d3d89a0.png)

You can see in the picture above the first line doesn't have buttons with centered text.

I'm sure the renderer is not called because I put some delays like the picture below but the first line of buttons appears immediately:

![image](https://user-images.githubusercontent.com/2490657/34776795-46d9ff9c-f618-11e7-9bd0-6c2fc12ac1cf.png)

**Comment by daniel-luberda** [comment]
It's a Xamarin.Forms issue, not FlowListView. This control has nothing to do how other views are used. It's entirely based on XF layout engine. Cheers.
