### ISSUE TITLE
FlowListView height issue

### ISSUE THREAD

**Issue by Puneetk207** [daniel-luberda/DLToolkit.Forms.Controls#168]
how can we manage flowlistview height dynamically according to item?
No hard code? No HeightRequest?

**Comment by krunalc** [comment]
I'm also looking for the fix of this problem. Originally ListView also have similar problem and I tried FlowListView in anticipation that this problem may have been taken care. But that is not the case. 

ListView basically gets fixed height and if Items are more than it displays scrollbar. However, when ListView is put inside the ScrollViewer then scrollbar of ListView stops working. Ideally in such case, ListView height should be as needed (i.e. as needed by items to be displayed) and scrollbar of ScrollViewer should take care of scrolling. 

Any suggestion to achieve this behavior with FLV?

**Comment by daniel-luberda** [comment]
> I'm also looking for the fix of this problem. Originally ListView also have similar problem and I tried FlowListView in anticipation that this problem may have been taken care. But that is not the case.

`FlowListView` is `ListView` internally, so same issues apply. I can't do anything about it. You can try to use  `HasUnevenRows = true`, a lot of issues were fixed in recent Xamarin.Forms versions.
