### ISSUE TITLE
FlowListView: is it possible to have distinct height for each "column"?

### ISSUE THREAD

**Issue by Goldstrike** [daniel-luberda/DLToolkit.Forms.Controls#169]
Hello,
I'm looking for the better way to implement a control that looks like a ListView on 2 columns.
The excpected result is something like [this](https://preview.ibb.co/kGYFjG/Flow_Layout.png).

The items of these 2 columns come from the same DataSource, and this DataSource can have between 1 and a dozen of items. The items must be splitted automatically (pair/impair), and when the user click on the button related to the item, this must open the item's detail page.

In a first time, I thought about using the DLToolkit FlowListView control , but it seems that the cells of each column must have the same height, so this control can't answer to my needs...

**_Could you confirm this, or suggest me another solution?_**

**Comment by daniel-luberda** [comment]
It's not possible to have different row height for columns with this control as it's based on `Xamarin.Forms.ListView`. Sorry.
