### ISSUE TITLE
FlowListView must add FlowLoadingTemplate to view items.

### ISSUE THREAD

**Issue by c-lamont** [daniel-luberda/DLToolkit.Forms.Controls#177]
In my `FlowListView` I have enabled `FlowIsLoadingInfiniteEnabled`.

However if I don't add a `FlowLoadingTemplate` then none of the items are shown.

I don't want to add a `FlowLoadingTemplate` because I show the loading somewhere else.

I have added a dummy `BoxView` with a height of 0 for now, but this still leaves a space at the bottom of the list and makes the list jerk when new items are added.

**Comment by daniel-luberda** [comment]
If `FlowEmptyTemplate` is `null` loading template is not shown at all. See this:  

- https://github.com/daniel-luberda/DLToolkit.Forms.Controls/blob/master/FlowListView/DLToolkit.Forms.Controls.FlowListView/FlowListView.cs#L745
- https://github.com/daniel-luberda/DLToolkit.Forms.Controls/blob/master/FlowListView/DLToolkit.Forms.Controls.FlowListView/FlowListView.cs#L838
