### ISSUE TITLE
Binding to FlowIsLoadingInfinite has no effect.

### ISSUE THREAD

**Issue by c-lamont** [daniel-luberda/DLToolkit.Forms.Controls#178]
No matter how I bind to `FlowIsLoadingInfinite`, it does not change.

Is using Xamvvm maybe the issue?

**Comment by daniel-luberda** [comment]
> Is using Xamvvm maybe the issue?

All controls here are MVVM framework independent, so it's definitely not a cause. 

There's an example here: https://github.com/daniel-luberda/DLToolkit.Forms.Controls/blob/master/Samples/DLToolkitControlsSamples/SamplesFlowListView/InfiniteLoadingPage.xaml

Make sure you follow this: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-basics/data-binding-basics
