### ISSUE TITLE
WinRT Windows desktop platform rendering problem

### ISSUE THREAD

**Issue by raV720** [daniel-luberda/DLToolkit.Forms.Controls#18]
There is problem with rendering first row on WinRT platform (desktop). On Android it works ok.
Items in first row (in this case buttons) does not display Text property. After rotating device text appears but it is not centered as expected.

XAML CODE:

```
    <flv:FlowListView x:Name="flowList">
        <flv:FlowListView.FlowColumnsTemplates>
            <flv:FlowColumnSimpleTemplateSelector ViewType="{x:Type controls:MainMenuButton}"/>
        </flv:FlowListView.FlowColumnsTemplates>
    </flv:FlowListView>
```

CONTROL CODE (simple button):

```
<Button xmlns="http://xamarin.com/schemas/2014/forms"
        xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
        x:Class="MZMT.View.Controls.MainMenuButton"
        BackgroundColor="Green"
        Text="{Binding .}">

</Button>
```

SETTING DATA SOURCE:
`flowList.FlowItemsSource = new List<string>() { "aaaaaaaaa", "bbbbbbbb", "cccccc", "dd", "asfasfasfafafas"};`

And a question: how to make FlowListView to wrap content? As I understand it is created for it, but I cannot manage to do it. I would like to create list of buttons with constant size, display them one next to other and wrap if not fit to screen.

**Comment by daniel-luberda** [comment]
Hi @raV720,

> There is problem with rendering first row on WinRT platform (desktop). On Android it works ok.
> Items in first row (in this case buttons) does not display Text property. After rotating device text appears but it is not centered as expected.
> 

Did you try to set correct `HorizontalOptions` flags? I think it may be rather `Xamarin.Forms` issue as `FlowListView` doesn't do any custom rendering and it's fully based on `Xamarin.Forms` layout mechanism. 

> And a question: how to make FlowListView to wrap content? As I understand it is created for it, but I cannot manage to do it. I would like to create list of buttons with constant size, display them one next to other and wrap if not fit to screen.

It's very easy. Just set `FlowAutoColumnCount` to `true` and set `FlowColumnDefaultMinimumWidth` which is used as a minimum desired column width.
