### ISSUE TITLE
How can i change row height dynamically?

### ISSUE THREAD

**Issue by FotalGoncharuk** [daniel-luberda/DLToolkit.Forms.Controls#183]
Can i change row height dynamically? For example with slider.

**Comment by Goncharyk** [comment]
I also saw this discussion https://github.com/daniel-luberda/DLToolkit.Forms.Controls/issues/11
Have you made any changes?

**Comment by daniel-luberda** [comment]
> Can i change row height dynamically? For example with slider.

It works exactly as `Xamarin.Forms.ListView` - the same approaches apply. Cheers.
