### ISSUE TITLE
Binding the properties of the ImageCropView

### ISSUE THREAD

**Issue by 1701413420** [daniel-luberda/DLToolkit.Forms.Controls#184]
Im new in Xamarin,
How can i bind all properties in a ViewModel without use the x:Name? im trie binding XOffset, YOffset, etc. but dont work

![image](https://user-images.githubusercontent.com/31360909/37786593-10e6c1dc-2dcb-11e8-8463-56290a9f3391.png)

**Comment by daniel-luberda** [comment]
Just read this: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-basics/data-binding-basics
