### ISSUE TITLE
FlowItemTappedCommand still not working on macOS

### ISSUE THREAD

**Issue by rossivc** [daniel-luberda/DLToolkit.Forms.Controls#185]
The FlowItemTappedCommand command is not called on macOS. The same XAML works on other platforms. Same issue as #156
(Visual Studio for Mac v 7.4.1, NuGet 4.3.1.4445, DLToolkit 2.0.10)

**Comment by daniel-luberda** [comment]
I made a Mac sample project. Any clues how could we fix this? It looks like Xamarin.Forms.Mac issue.

**Comment by daniel-luberda** [comment]
It's a Xamarin.Forms issue. More here: 

- https://github.com/daniel-luberda/DLToolkit.Forms.Controls/issues/165
- https://github.com/xamarin/Xamarin.Forms/issues/1658

Not fixed yet
