### ISSUE TITLE
FlowListView with long tapped

### ISSUE THREAD

**Issue by cansado2930** [daniel-luberda/DLToolkit.Forms.Controls#186]
Hi, 
I would like to use your flowlistview instead of a listview because it is more usefull. But I have "small" problem On the listview I have to do "render" in order to get longtapped event. Is it supported? Or, Are there some way in order to get it? I need it to show user options when they do a long tap.
Thank you

**Comment by daniel-luberda** [comment]
This component supports any view type. Just use this: 

- https://alexdunn.org/2017/12/27/xamarin-tip-xamarin-forms-long-press-effect/
- https://github.com/ice-j/LongPressGesture
- https://github.com/mrxten/XamEffects

**Comment by jamesingreersc** [comment]
Has anyone been able to do this with FlowListView. I tried all 3 links above and none worked. This is the xaml I am tying to wire up a long press against.

            <controls:FlowListView
                Grid.Row                               ="5"
                Grid.Column                            ="2"
                BackgroundColor                        ="Transparent"
                FlowColumnMinWidth                     ="100"
                FlowItemTappedCommand                  ="{Binding Selected}"
                FlowItemsSource                        ="{Binding Thumbnails}"
                FlowLastTappedItem                     ="{Binding LastTappedItem}"
                HasUnevenRows                          ="True"
                SeparatorVisibility                    ="None">
                <controls:FlowListView.FlowColumnTemplate>
                    <DataTemplate>

                        <Grid>
                            <Grid.ColumnDefinitions>
                                <ColumnDefinition Width="*" />
                                <ColumnDefinition Width="*" />
                            </Grid.ColumnDefinitions>
                            <Grid.RowDefinitions>
                                <RowDefinition Height  ="35" />
                                <RowDefinition Height  ="*" />
                            </Grid.RowDefinitions>
                            <Image x:Name              ="ThumbnailImage"
                                Grid.RowSpan           ="2"
                                Grid.ColumnSpan        ="2"
                                Margin                 ="3.85"
                                Aspect                 ="AspectFill"
                                BackgroundColor        ="Transparent"
                                HeightRequest          ="100"
                                Source                 ="{Binding Source}"
                                WidthRequest           ="100" >
                            </Image>
                        </Grid>
                    </DataTemplate>
                </controls:FlowListView.FlowColumnTemplate>
            </controls:FlowListView>
