### ISSUE TITLE
Orientation changes don't recalculate Auto Column Count

### ISSUE THREAD

**Issue by bblocher** [daniel-luberda/DLToolkit.Forms.Controls#19]
Switching from landscape to portrait doesn't work when using RecycleElement for the ListViewCachingStrategy.

For example if you're in portrait and are four columns wide, when you rotate to landscape the column count should recalculate and increase, but remains at four.

**Comment by daniel-luberda** [comment]
I am preparing a new release, that fix will be included soon.
