### ISSUE TITLE
ImageCropView not working with bundled resources

### ISSUE THREAD

**Issue by tcomben** [daniel-luberda/DLToolkit.Forms.Controls#190]
It seems as though resources included in a Xamarin app, can not be displayed in the ImageCropView. I've attached a sample solution to illustrate what I'm talking about.

If I include an image in the Resources/drawable folder in Android, add it as an asset in iOS, or include it in the root of the UWP project, the image is not displayed in the ImageCropView. 

Here's the XAML where I'm able to display the image:

                <Label Text="ImageCropView" TextColor="White"/>
                <imgcrop:ImageCropView Source="hotair.jpg"
                                       HorizontalOptions="FillAndExpand"
                                       VerticalOptions="FillAndExpand"
                                       WidthRequest="50"/> 
                
                <Label Text="Image" TextColor="White"/>
                <Image Source="hotair.jpg"
                       HorizontalOptions="FillAndExpand"
                       VerticalOptions="FillAndExpand"
                       WidthRequest="50"/> 

                <Label Text="CachedImage" TextColor="White"/>
                <ffimageloading:CachedImage Source="hotair.jpg"
                                            HorizontalOptions="FillAndExpand"
                                            VerticalOptions="FillAndExpand"
                                            WidthRequest="50"/> 

![androidimagecropview](https://user-images.githubusercontent.com/295058/39013112-652ad6b4-43e4-11e8-9353-9a61a7231fe7.png)
![iosimagecropview](https://user-images.githubusercontent.com/295058/39013113-6538a906-43e4-11e8-85ef-47384967819f.png)
![uwpimagecropview](https://user-images.githubusercontent.com/295058/39013114-654bb2a8-43e4-11e8-9890-d6153b5d895a.png)
[ImageCropSourceIssue.zip](https://github.com/daniel-luberda/DLToolkit.Forms.Controls/files/1929458/ImageCropSourceIssue.zip)

Thanks

**Comment by tcomben** [comment]
Thanks!

**Comment by kengdev** [comment]
Hi, How can you fixed this issue? I have the same problem. Please help.

**Comment by tcomben** [comment]
@kengdev 

I think this was fixed about a year ago. I would make sure you're using the latest version, and if it's still not working submit an issue to them.
