### ISSUE TITLE
Aspect on ImageCropView

### ISSUE THREAD

**Issue by tcomben** [daniel-luberda/DLToolkit.Forms.Controls#191]
Would it be possible to add the "Aspect" property on ImageCropView? 

I'd like for the image to look like an "AspectFit" image when a page loads, and then the user can zoom in/out within the image. I've tried using the vertical and horizontal options to achieve what I'm looking for without luck.

Thanks.

**Comment by daniel-luberda** [comment]
Implemented, cheers :)

**Comment by tcomben** [comment]
Thanks!
