### ISSUE TITLE
what is the status of this project?

### ISSUE THREAD

**Issue by hugoterelle** [daniel-luberda/DLToolkit.Forms.Controls#194]
Hi, 

Just to know what is the status of this project because there's some annoying issues when using the libraries and it seems the project was abandonned.

@daniel-luberda do you still plan to work on this project?

**Comment by daniel-luberda** [comment]
Hi @hugoterelle, @orestesgaolin 

I use it all the time in my internal projects, so it's still maintained. I didn't have time to push all the fixes, changes on a public repo though. I'll try do it in a week or so and review all the issues. 

Cheers.

**Comment by orestesgaolin** [comment]
Thanks for the update!

**Comment by vlkam** [comment]
Status of project: It's awesome !

**Comment by rredoh** [comment]
How about now?
