### ISSUE TITLE
Alternative to ViewCell

### ISSUE THREAD

**Issue by crazych** [daniel-luberda/DLToolkit.Forms.Controls#199]
Hello,
I want to set BackgroundGradient for a cell using another external component.
Its required to be placed in ViewCell to work, but this can not be achieved here.
Is there an alternative way of achieving it?

**Comment by daniel-luberda** [comment]
FlowListView uses `View` not `ViewCell`. You can simply use something like: https://github.com/DevsDNA/GradientBoxView
