### ISSUE TITLE
Request: A few additional samples

### ISSUE THREAD

**Issue by ravensorb** [daniel-luberda/DLToolkit.Forms.Controls#2]
Any chance you could add a few additional samples that show other types of configurations?  

Thoughts on scenarios
- Simple Data Template (basic usage with 1 template)
- Horizontal Scroll Grid (1 row)

**Comment by daniel-luberda** [comment]
Hi @ravensorb,

>Simple Data Template (basic usage with 1 template)

Sure. Could you give more details?

>Horizontal Scroll Grid (1 row)

Horizontal scrolling is not supported as Xamarin.Forms `ListView` doesn't support that (and `FlowListView` derives from it)

**Comment by ravensorb** [comment]
I was looking over the sample and am having a little bit of a tough time figuring out how to use it :)

Example: 
* Line 17 and 18 as well as 19 and 20 appear to be duplicate lines.  But I am not sure why each entry is being declared twice
* How would I use this for a single data template (one template for all items) in a Grid type layout?  Say a Grid of Pictures (like a gallery)

**Comment by daniel-luberda** [comment]
>Line 17 and 18 as well as 19 and 20 appear to be duplicate lines. But I am not sure why each entry is being declared twice

What file are you referring to?:)

>How would I use this for a single data template (one template for all items) in a Grid type layout? Say a Grid of Pictures (like a gallery)

I'll upload some new better examples today.

**Comment by ravensorb** [comment]
I suppose a link the specific file would help :smile:

https://github.com/daniel-luberda/DLToolkit.Forms.Controls/blob/master/Examples/Pages/FlowListViewExpandPage.xaml

**Comment by daniel-luberda** [comment]
Column definitions (4 columns with 2 layout used multiple times). The new thing (not on nuget yet) is FlowAutomaticColumnCount with FlowAutomaticColumnMinimumWidth. You define just one column template and set it to true, and column number will be automatically calculated to fill container.

**Comment by daniel-luberda** [comment]
FlowSelectors.CustomAdvancedTemplateSelector is advanced template selector (basing on current binding context - it can provide different template for a cell for every item)

**Comment by ravensorb** [comment]
So do that mean if I have 6 columns, I need to define the type 6 times?  Wouldn't it be easier to have it match a selector to an object type during binding -- that would allow more reuse (and less copy/pasting in the xaml)

**Comment by daniel-luberda** [comment]
You can have one definition only with `FlowAutomaticColumnCount` set to true. 

You don't need to define any type as `FlowColumnSimpleTemplateSelector` is built in and can be used for simple scenarios. Multiple column definitions are used in scenarios where you want left/center/right items to be different - so it's needed.

**Comment by daniel-luberda** [comment]
Why selectors? It's because you can have any cell to have any type of view dynamically basing or binding context. I didn't find simpler way to do it.

**Comment by daniel-luberda** [comment]
I started to update some samples

The simplest one is: 

## C# 
- [SimpleExamplePage.cs](https://github.com/daniel-luberda/DLToolkit.Forms.Controls/blob/master/Examples/ExamplesFlowListView/Pages/SimpleExamplePage.cs)
- [SimpleExampleViewModel.cs](https://github.com/daniel-luberda/DLToolkit.Forms.Controls/blob/master/Examples/ExamplesFlowListView/ViewModels/SimpleExampleViewModel.cs)

## XAML
- [SimpleExampleXamlPage.xaml](https://github.com/daniel-luberda/DLToolkit.Forms.Controls/blob/master/Examples/ExamplesFlowListView/Pages/SimpleExampleXamlPage.xaml)
- [SimpleExampleXamlPage.xaml.cs](https://github.com/daniel-luberda/DLToolkit.Forms.Controls/blob/master/Examples/ExamplesFlowListView/Pages/SimpleExampleXamlPage.xaml.cs)
- [SimpleExampleXamlViewModel.cs](https://github.com/daniel-luberda/DLToolkit.Forms.Controls/blob/master/Examples/ExamplesFlowListView/ViewModels/SimpleExampleXamlViewModel.cs)

**Comment by TimeBomb006** [comment]
> How would I use this for a single data template (one template for all items) in a Grid type layout? Say a Grid of Pictures (like a gallery)

Forgive me if it's obvious, but is it possible to just define an inline column template rather than abstracting it out to a view? I'm trying to create a gallery similar to the previous request and it's not immediately clear to me.

**Comment by daniel-luberda** [comment]
@TimeBomb006 You mean that you don't want to have view definition defined in a separate file? If yes it's not possible yet,  but the new release will have this (standard Forms data templates). 

If you want to have auto generated column count just use FlowAutoColumnCount and FlowMinimumWidth, property and define just one column template. Column count will be calculated automatically then.

**Comment by daniel-luberda** [comment]
Samples should be better now.
