### ISSUE TITLE
An error occurred while retrieving package metadata

### ISSUE THREAD

**Issue by petersondrew** [daniel-luberda/DLToolkit.Forms.Controls#20]
Looks like something happened either during creation of the 1.0.7 nuget package, or on upload, as we receive the following error any time we open nuget package manager or try to update/install packages:
`An error occurred while retrieving package metadata for 'DLToolkit.Forms.Controls.FlowListView.1.0.7'`This was reproducible on multiple machines using Visual Studio 2015 with the latest nuget package manager (tested with command line client as well).

The workaround for us, for the time being, was toe re-compress the nupkg file in our packages directory using a zip utility. I figured this out by running the nuget command line utility with the `-Verbosity detailed` flag and found this error in the output:
`System.IO.FileFormatException: File contains corrupted data`
So something in the zip headers is throwing off the nuget client.

Not sure if a re-upload of 1.0.7 will resolve this, or if there's a deeper issue with the nuget client you used to package this.

**Comment by daniel-luberda** [comment]
@petersondrew  There's a new 1.0.8 package. Could you check it?

**Comment by CeSeeYee** [comment]
@daniel-luberda I would like to ask which nuget version is the most stable for Xamarin.Forms 2.3.2.127?

**Comment by daniel-luberda** [comment]
@CeSeeYee I would use the most recent one.
