### ISSUE TITLE
TagEntry example crash

### ISSUE THREAD

**Issue by Depechie** [daniel-luberda/DLToolkit.Forms.Controls#21]
Not sure why, but running the repo on latest forms version 2.3.2.127 will result in a exception when trying to open the TagEntryView example from the example app.

Other flow views are working...

**Comment by opcodewriter** [comment]
Hmm, any update on this? Is it reproducible ? 
@Depechie What is the error you have? On which Android version did you get this?

**Comment by Depechie** [comment]
Don't have my dev device here, but  I only tested on iOS ( iPhone )

**Comment by daniel-luberda** [comment]
Fixed & nuget released

**Comment by Depechie** [comment]
Awesome, thanks!!

**Comment by opcodewriter** [comment]
@daniel-luberda Sorry, I can't understand what was the issue looking at the commit, what was the reason of the crash? I didn't have any issues.

**Comment by daniel-luberda** [comment]
The issue was quite funny :) 

https://github.com/daniel-luberda/DLToolkit.Forms.Controls/commit/8ed4ed3ff2542e3126a69635d46939642816ffc2#diff-635a89673f8eeffa34948f1f7e58ac89R90

`150f` instead `150d`

**Comment by opcodewriter** [comment]
Thanks. I'm a bit confused, because I think it worked fine for me with latest Xamarin Forms.
