### ISSUE TITLE
FlowListView  - questions

### ISSUE THREAD

**Issue by opcodewriter** [daniel-luberda/DLToolkit.Forms.Controls#22]
1. Can I specify a DataTemplate for the cell?
   I see it only works with the FlowColumnTemplateSelector but this one returns Type which later used to create the instance like this:
   `var view = (View)Activator.CreateInstance(columnTypes[i]);`
2. If I change the width and height of a cell, does it refresh correctly?

**Comment by daniel-luberda** [comment]
Hi @opcodewriter,

> Can I specify a DataTemplate for the cell?

Yes, `FlowColumnTemplateSelector` is just a sample implementation of `FlowColumnTemplateSelector`. You can create your own: 

```C#
	public class CustomAdvancedTemplateSelector : FlowColumnTemplateSelector
	{
		public override Type GetColumnType(object bindingContext)
		{
			// YOUR CUSTOM LOGIC HERE

			if (bindingContext == null)
				return typeof(ContentView);

			return typeof(FlowListViewExpandCell);
		}
	}
```

> If I change the width and height of a cell, does it refresh correctly?

`FlowListView` is `ListView` derivative, some the same behavior is expected as in `ListView`.

**Comment by opcodewriter** [comment]
@daniel-luberda Thanks but, for the 1st question, it won't work

I need to be able to give a `DataTemplate` not a `Type` which you create with `Activator.CreateInstance(columnTypes[i])`

I realized this is actually not possible, I have to modify the code of the library to use `DataTemplate`.

In my opinion, supporting `DataTemplate` is important for people who use `DataTemplate` defined in XAML and not create `View` manually in code.

**Comment by daniel-luberda** [comment]
I also wanted to use `DataTemplate` but finally because of performance issues, I didn't. Please notice, `DataTemplate` always creates a new view instance. That's not what we want here (view reusing, etc).

**Comment by daniel-luberda** [comment]
BTW: You can still define Views in XAML, the only difference is, it's a separate file.

**Comment by opcodewriter** [comment]
You also create a new instance now, so using a DataTemplate would be the same thing.

But yes, you would need to modify `RowLayoutChanged` to check for modifications:
just need to cache the DataTemplates.

Something like this:

```
public class FlowListViewInternalCell : ViewCell
{
        readonly IList<DataTemplate> _flowColumnDataTemplates;`
      
        protected override void OnBindingContextChanged()
        {      
              ....
            else // RECREATE COLUMNS
            {
                if (_rootLayout.Children.Count > 0)
                {
                    _rootLayout.Children.Clear();
                    _flowColumnDataTemplates.Clear();  // clear the data templates
                }

                for (int i = 0; i < containerCount; i++)
                {
                    var view = (View)columnTypes[i].CreateContent();

                    _flowColumnDataTemplates.Add(columnTypes[i]);  // save the data templates

                    view.GestureRecognizers.Add(new TapGestureRecognizer()
                    {
                        Command = new Command(async (obj) =>
                        {
                            await ExecuteTapGestureRecognizer(view);
                        })
                    });

                    SetBindingContextForView(view, container[i]);
                    AddViewToLayout(view, containerCount, i);
                }
            }
              ....
        }

        private bool RowLayoutChanged(int containerCount, IList<DataTemplate> columnTypes)
        {
            // Check if desired number of columns is equal to current number of columns
            if (_rootLayout.Children.Count != containerCount)
            {
                return true;
            }
            else
            {
                // Check if desired column view types are equal to current columns view types
                for (int i = 0; i < containerCount; i++)
                {
                    if (_flowColumnDataTemplates[i] != columnTypes[i])
                    {
                        return true;
                    }

                    //if (_rootLayout.Children[i] != columnTypes[i])
                    //{
                    //    return true;
                    //}
                }
            }

            return false;
        }
}

**Comment by opcodewriter** [comment]
public abstract class FlowColumnTemplateSelector
	{
		public abstract DataTemplate GetColumnType(object bindingContext);
	}

**Comment by daniel-luberda** [comment]
> You also create a new instance now, so using a DataTemplate would be the same thing.

Not exactly. I don't create instances every time (they're reused if possible, eg. view type didn't change). Take a look here: https://github.com/daniel-luberda/DLToolkit.Forms.Controls/blob/master/FlowListView/DLToolkit.Forms.Controls.FlowListView/FlowListViewInternalCell.cs#L253-L254

**Comment by opcodewriter** [comment]
Yes, I know. You can achieve same thing with `DataTemplate`, you just need to save them in the `FlowListViewInternalCell` so you can compare them with the new ones in the `RowLayoutChanged`

See my code.

**Comment by daniel-luberda** [comment]
I didn't see your code yet as I'm not at home. Do you mean comparing `DataTemplate` type? If it's possible, we could `Obsolete` old template selectors and create new `DataTemplate` based. But:

`FlowListView` need a `List` of `DataTemplates` - I had some problems with it (it wasn't supported). I don't know if anything changed in that matter.

**Comment by opcodewriter** [comment]
What problems did you have exactly? Maybe I can help.

**Comment by daniel-luberda** [comment]
This works:

```XML
<DataTemplate>
	<ContentView/>
</DataTemplate>
```

This doesn't:

```XML
<DataTemplates>
	<DataTemplate>
		<ContentView/>
	</DataTemplate>
	<DataTemplate>
		<ContentView/>
	</DataTemplate>
</DataTemplates>
```

We need multiple `DataTemplate` definitions.

**Comment by opcodewriter** [comment]
well, you could still keep the FlowColumnTemplateSelector, something like this:

```
<dltoolkit:FlowListView.FlowColumnsTemplates>
                    <dltoolkit:FlowColumnTemplateSelector Template="{StaticResource MyTemplate1}" />
                     <dltoolkit:FlowColumnTemplateSelector Template="{StaticResource MyTemplate2}" />
                 </dltoolkit:FlowListView.FlowColumnsTemplates>
</dltoolkit:FlowListView.FlowColumnsTemplates>

```

**Comment by daniel-luberda** [comment]
@opcodewriter I have an idea: 

- `DataTemplate FlowColumnTemplate` property (not a list, just a single one)
- `int FlowColumntCount` property which will be used when `FlowAutoColumnCount` is disabled
- Multiple templates can be solved with `DataTemplateSelector`
- That way, we still have full XAML syntax support

What do you think?

**Comment by jamesl77** [comment]
`DataTemplateSelector` derives from `DataTemplate`. So I think you can just have one property called `DataTemplate FlowItemTemplate`. 
 Xamarin Forms ListView does it like this for the `ItemTemplate` property: https://blog.xamarin.com/customizing-list-view-cells-xamarin-forms-datatemplateselector/

Optionally, if you want to offer the ability to select based on item's index, you could have a FlowItemTemplateSelector which looks like this:

```
public abstract class FlowItemTemplateSelector : DataTemplate
{
         public abstract DataTemplate SelectTemplate(int index, object item);
}
```

I am not sure about having both `FlowColumnCount` and `FlowAutoColumnCount`. Maybe have just `int? FlowColumnCount` which by default is null, meaning control auto computes the number of columns based on FlowLisView's width and flow item's width.
I would change `FlowColumnDefaultMinimumWidth` to just `int? FlowColumnWidth`. If it's null and you need item width, use the item's `MinimumWidth`.

**Comment by daniel-luberda** [comment]
@jamesl77 These are really nice suggestions. I'll implement it and obsolete old properties (they'll still work for compatibility).

**Comment by opcodewriter** [comment]
Compatibility is an issue, but in the same time keeping the obsolete code and mixing with new code, just for the sake of compatibility, I'm not sure is a good thing on the long run. At some point you need to get rid of it, there's a reason why it's obsolete I assume :)
Why not go to a major version of the library? The library right now is stable enough I guess? So people who use your library at current version are fine with it.

**Comment by daniel-luberda** [comment]
Nuget 2.0.0-alpha1 released. I also created new samples project: 

https://github.com/daniel-luberda/DLToolkit.Forms.Controls/blob/master/Samples/DLToolkitControlsSamples/SamplesFlowListView/SimplePage.xaml

**Comment by daniel-luberda** [comment]
```XML
<flv:FlowListView FlowColumnCount="3" FlowItemsSource="{Binding Items}" 
	SeparatorVisibility="None" HasUnevenRows="false"
	FlowItemTappedCommand="{Binding ItemTappedCommand}" FlowLastTappedItem="{Binding LastTappedItem}">

	<flv:FlowListView.FlowColumnTemplate>
		<DataTemplate>
			<Label HorizontalOptions="Fill" VerticalOptions="Fill" 
				XAlign="Center" YAlign="Center" Text="{Binding Title}"/>
		</DataTemplate>
	</flv:FlowListView.FlowColumnTemplate>

</flv:FlowListView>		
```

**Comment by opcodewriter** [comment]
So which way did you go in the end? Mixing old and new?

**Comment by daniel-luberda** [comment]
For now, no compatibility. But it's very easy to add as we only add old properties and translate it to the new `DataTemplate` based code. It won't have any impact for internals. What do you think?

**Comment by opcodewriter** [comment]
I'm for clean code. Like I said before, the library is small, and pretty stable. No reason to keep deprecated code.

**Comment by 3-50** [comment]
Please, add compatibility in the new version. Why do we need to rewrite the code working, and it works well.

**Comment by opcodewriter** [comment]
@3-50 using current released version still works and will still work. I can't speak in the name of @daniel-luberda  but I think if any critical bug appear it's still going to be fixed in current released version.

**Comment by daniel-luberda** [comment]
@3-50 The new API allows you to use the same source data which is used in a Xamarin.Forms `ListView`, just with column support. Old one is quite stable, I don't know of any issues with it. If some issues will be found in old version, I'll publish bug fixes release, so don't worry.

**Comment by 3-50** [comment]
@opcodewriter, @daniel-luberda  Thank you for your answer.
