### ISSUE TITLE
Item Expanding per row

### ISSUE THREAD

**Issue by Dageezah** [daniel-luberda/DLToolkit.Forms.Controls#241]
Suppose we have a FlowListView with 3 columns and 20 items, Is it possible to have a specific item (lets say the first item on the third row) span 3 columns?

**Comment by vlkam** [comment]
It's not possible without modification
But internally the row of FlowList is Grid and you can try to span columns

![image](https://user-images.githubusercontent.com/7336057/50766400-1a725c80-128a-11e9-8de0-0e6183f971bb.png)

**Comment by Dageezah** [comment]
Good Stuff - Thanks vlkam
