### ISSUE TITLE
Missing reference on the Android project

### ISSUE THREAD

**Issue by IeuanWalker** [daniel-luberda/DLToolkit.Forms.Controls#258]
Xamarin.Forms - 3.6

Error on every version above 2.0.4. Only on the Android project.
![image](https://user-images.githubusercontent.com/6544051/55488990-fde78580-5628-11e9-9d53-19f2b3404439.png)
![image](https://user-images.githubusercontent.com/6544051/55489278-89611680-5629-11e9-9fb7-35e53007708c.png)

**Comment by snice1981** [comment]
Hi IeuanWalker

Same problem here.  Did you manage to fix it?

**Comment by IeuanWalker** [comment]
@snice1981 nope and it is also causing us issues with VS2019 for some reason.
We are planning to update to XF 4.1 and take advantage of some of the new features which means we can remove this NuGet.

**Comment by IeuanWalker** [comment]
Closing as no I no longer use this package
