### ISSUE TITLE
Unable to build example projects

### ISSUE THREAD

**Issue by bharath8d** [daniel-luberda/DLToolkit.Forms.Controls#26]
I am new to GitHub. I downloaded the code and tried to build the solution to go through some of the example but example projects are failing to get build as few types like FlowColumnTemplateSelector are missing. Could you please let me know if I am missing any step?

**Comment by daniel-luberda** [comment]
The old one samples were obsolete, try the new ones: https://github.com/daniel-luberda/DLToolkit.Forms.Controls/tree/master/Samples

**Comment by bharath8d** [comment]
Thanks!
