### ISSUE TITLE
DLToolkit.Forms.Controls.FlowListView 2.0.0 is not compatible with UAP

### ISSUE THREAD

**Issue by 3-50** [daniel-luberda/DLToolkit.Forms.Controls#27]
After updating to 2.0.0:
1) DLToolkit.Forms.Controls.FlowListView 2.0.0 is not compatible with UAP,Version=v10.0. Some packages are not compatible with UAP,Version=v10.0.

I managed to solve my problem. Solution:
nugget.exe locals all -clear

2) The type or namespace name "DLToolkit.Forms.Controls" could not be found (are you missing a using directive or an assembly reference?)"

Solution:
?

**Comment by daniel-luberda** [comment]
Hi @3-50,

1. What is you project PCL version? Did you try to remove package and then install it once again? 
2. Namespace didn't change. If you're using XAML only, remember to call `FlowListView.Init()` somewhere.

**Comment by 3-50** [comment]
Hello @daniel-luberda,
 I managed to solve my problems (http://imgur.com/a/EYpYy), cleared the nuget local cache and reinstall. Thank you.

**Comment by daniel-luberda** [comment]
@3-50 Great 👍
