### ISSUE TITLE
Is it possible to add a BackgroundImage property to the FlowListView InternalCell?

### ISSUE THREAD

**Issue by Emasoft** [daniel-luberda/DLToolkit.Forms.Controls#29]
Is it possible to add a BackgroundImage property to the FlowListView InternalCell?

**Comment by daniel-luberda** [comment]
Hi @Emasoft I don't think we should add it (performance reasons). You can easily do it yourself defining your template like this: 

```XML
<Grid>
<Image source="pic.png"/>
<Label Text="Some text"/>
<Grid>
```
