### ISSUE TITLE
Since ios 15 reload from event handler leads to immense flickering!

### ISSUE THREAD

**Issue by innomotionmedia** [daniel-luberda/DLToolkit.Forms.Controls#299]
I reload items from a simple function.

If I call the reload function statically,

EG:

       LoadMoreAds(4);
       LoadMoreAds(8);
       LoadMoreAds(12);
       LoadMoreAds(16);

Everything works fine.

But If I put this inside the event handler for item appearing to make it dinamically reload:

     private void listview_allAds_FlowItemAppearing(object sender, ItemVisibilityEventArgs e)
            {
                  TinyAd current = e.Item as TinyAd;
                
                  if (current == contentOfListView[contentOfListView.Count-1])
                  {
                    LoadMoreAds();
                  }
    
    }

The items that are already inside the observable collection flicker badly for a few frames until the reload is done. then they are fine until the next reload happens. 

THis is my list:

      <flv:FlowListView
                        Grid.Row="1"
                        BackgroundColor="Transparent"
                        Scrolled="listview_allAds_Scrolled"
                        VerticalOptions="Fill"
                        FlowItemAppearing="listview_allAds_FlowItemAppearing"                 
                        Refreshing="listview_allAds_Refreshing"
                        FlowColumnCount="1"
                        IsPullToRefreshEnabled="True"
                        Margin="5,0,5,0"
                        VerticalScrollBarVisibility="Never"
                        HasUnevenRows="True"
                        x:Name="listview_allAds" />

Has anyone experienced a similiar issue?

**Comment by SolarisYan** [comment]
I have the same issue, have you solved it

**Comment by innomotionmedia** [comment]
No, i switched to different components... :(
