### ISSUE TITLE
some errors

### ISSUE THREAD

**Issue by dg782** [daniel-luberda/DLToolkit.Forms.Controls#30]
Hi,

Today I download your code then :
- in solution explorer I remove two IOS projects
- Restore Nuget Packages
- clean solution then rebuild 

-->  4 errors and 10 warnings

There is also errors in reference.

See the linked images.

Thanks

![error_1](https://cloud.githubusercontent.com/assets/12531027/19618264/6423ae40-9845-11e6-9b2f-0d9327447a0d.png)
![error_2](https://cloud.githubusercontent.com/assets/12531027/19618265/6c454c14-9845-11e6-9feb-ab4b9721e71e.png)

**Comment by daniel-luberda** [comment]
@dg782 You probably have some problems with nuget cache. Please try clear it then remove all `bin` , `obj` & `packages` folders in your projects folders, clean solution and build.

**Comment by daniel-luberda** [comment]
BTW: You don't need to build all projects. (`SpanView` is not finished yet). Just the samples or working controls.
