### ISSUE TITLE
WinRT FlowListViewInternalCellRenderer disable row highlight ?

### ISSUE THREAD

**Issue by r3vv** [daniel-luberda/DLToolkit.Forms.Controls#31]
Hi,

I'm currently trying to get off the row highlight on WinRT platform.
I'm seeing that there's no example of how to do it, and after few tries of different methods of changing the Cell Template and the Transitions for my control i can't find the right way to do it.
Do you have a solution for that ?

Thanks a lot,

**Comment by daniel-luberda** [comment]
Something like this (but from code): http://stackoverflow.com/questions/38705396/how-to-change-selectedbackground-in-listviewitempresenter-inside-a-gridview

**Comment by r3vv** [comment]
Well i can't seem to make that work in my custom renderer, i'll try to post on XF Forums for other ideas, maybe someone will be able to help. I'll update here anyway as soon as i fix this :)
Thanks,

**Comment by daniel-luberda** [comment]
@r3vv Any news about this?

**Comment by r3vv** [comment]
@daniel-luberda unfortunately no. I changed my way of approach and created a WrapLayout with an ItemsSource to get a semblant of gallery without the animations from the Windows ListView. But it's pretty annoying to do it this way since you can't get all the nice features from the listview. It's the same with normal listview. If you want to create some repeated content without clickable animation on the cell itself.

**Comment by r3vv** [comment]
@daniel-luberda Little update : I managed to do it for a normal listview this should be the same way to implement it on your FlowListView.

   ```
 public class AlternateListViewRenderer : ListViewRenderer
    {
        protected override void OnElementChanged(ElementChangedEventArgs<Xamarin.Forms.ListView> e)
        {
            base.OnElementChanged(e);
            if (this.List != null)
                this.List.ItemContainerStyle = (Style)App.Current.Resources["ListViewItemStyle1"];
        }

    }
```

this is the CustomRenderer i'm using for my listview

And the style is this :

      <Style x:Key="ListViewItemStyle1" TargetType="ListViewItem">
                <Setter Property="Template">
                    <Setter.Value>
                        <ControlTemplate TargetType="ListViewItem">
                            <ContentPresenter/>
                        </ControlTemplate>
                    </Setter.Value>
                </Setter>
            </Style>

Normally the ContentPresenter is a ListViewItemPresenter by changing it to a ContentPresenter i'm disabling all animations on the cell since i don't want it to be clicked.

**Comment by YZahringer** [comment]
This also works:
```cs
[assembly: Xamarin.Forms.Platform.UWP.ExportRenderer(typeof(DLToolkit.Forms.Controls.FlowListView), typeof(App.UWP.Controls.AlternateListViewRenderer))]
namespace App.UWP.Controls
{
    using Xamarin.Forms.Platform.UWP;

    public class AlternateListViewRenderer : ListViewRenderer
    {
        protected override void OnElementChanged(ElementChangedEventArgs<Xamarin.Forms.ListView> e)
        {
            base.OnElementChanged(e);

            if (List != null)
                List.IsHitTestVisible = false;
        }
    }
}
```

**Comment by daniel-luberda** [comment]
@r3vv @YZahringer That's cool. Thanks! :)

**Comment by zuckerthoben** [comment]
Can you link to this on the front page (Readme)? I just lost an hour trying to write my own CustomRenderer for ViewCellRenderer on UWP.

**Comment by zippo227** [comment]
I just lost an hour looking for how to do this as well.

**Comment by daniel-luberda** [comment]
Also this https://github.com/daniel-luberda/DLToolkit.Forms.Controls/commit/679876170f2ca3ce9c019db6570277ab867f0efb should help. I'll also add @YZahringer solution to README.md

Thanks
