### ISSUE TITLE
Row height issue

### ISSUE THREAD

**Issue by daviddotmac** [daniel-luberda/DLToolkit.Forms.Controls#35]
Hi Daniel, 

Having a little issue with height of rows in the FlowListView plugin.

Here is my XAML.

`

    <flv:FlowListView FlowItemsSource="{Binding Listings2}" HasUnevenRows="True" RowHeight="-1">

      <flv:FlowListView.FlowColumnTemplate>
        <DataTemplate>
          
          <Label VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand" LineBreakMode="WordWrap" Text="Lorem ipsum dolor sit amet, consectetur adipiscing elit."></Label>
          
        </DataTemplate>
        
      </flv:FlowListView.FlowColumnTemplate>

    </flv:FlowListView>`

Unfortunately when viewing this in android all i get is the first word displayed repeatedly. I had hoped setting unevenrows to true and rowheight to -1 that these would stretch automatically. Am I missing something obvious? 

Here is a screenshot of the output.

Thanks,
Dave.

![lorem](https://cloud.githubusercontent.com/assets/1466298/19900472/8ad9279a-a05b-11e6-985d-89ac4594e7d1.JPG)

**Comment by daviddotmac** [comment]
I have noticed on other issues that seem to match #17 and #16 you say "You just need to set correct HorizontalOptions and VerticalOptions layout flags on a main cell view. " could you please give me a pointer as to where in my code to put these? I have tried on every element in the XAML above pretty much, but to no avail. 

I do notice that if I set a widthRequest on the label this fixes it, but I'm hoping to put this on different device widths so was reluctant to start hard coding widths,

Thanks,
Dave.

**Comment by daniel-luberda** [comment]
It should be possible with 2.0.1 which uses `Grid` internally. Old behavior can be enabled back with `FlowUseAbsoluteLayoutInternally` parameter.

**Comment by daviddotmac** [comment]
Made absolutely no changes other than updating to 2.0.1 and it worked! Thanks very much! 👍
