### ISSUE TITLE
FlowListView error Failed to resolve "System.Object Xamarin.Forms.ElementTemplate::CreateContent()"

### ISSUE THREAD

**Issue by cloxure** [daniel-luberda/DLToolkit.Forms.Controls#36]
I have a Xamarin forms app and I am getting the following error using the simple page example everytime I build:

> Error		Failed to resolve "System.Object Xamarin.Forms.ElementTemplate::CreateContent()" reference from "Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null"	yuu.iOS

**Comment by daniel-luberda** [comment]
I'll need more details or reproduction. Did you restore nuget packages?

**Comment by cloxure** [comment]
I am using the latest version of the nugget package 2.0.1 and Xamarin forms 2.3.2.127.

I've added FlowListView.Init(); in the AppDelete class. Also added the nugget package to every project on the solution.

**Comment by cloxure** [comment]
the error is thrown even without any Xaml or C# code, only using the FlowListView.Init();.

I am on Visual Studio 2015 Community edition.

**Comment by daniel-luberda** [comment]
From the exception, it looks like you're having some problems with `Xamarin.Forms` (`Xamarin.Forms.Core`), not `FLowListView`. Did you try to clean solution, remove all `bin` and `obj` folders?

**Comment by cloxure** [comment]
I will try that and I will let you know.

**Comment by daniel-luberda** [comment]
@cloxure Any news? BTW: There's a new release.

**Comment by cloxure** [comment]
@daniel-luberda  I was able to use the component, just updating to the latest Xamarin.Forms did the trick!.

Thanks.
