### ISSUE TITLE
FlowColumnExpand = None does not work

### ISSUE THREAD

**Issue by NelsonSantos** [daniel-luberda/DLToolkit.Forms.Controls#37]
Hi Daniel...

I think that the default behavior of the FlowColumnExpand = Nome is not working properly.

I have a flow with FlowColumnCount = 3 and the ItemsSource have 5 items.

The last 2 on second row expand equal and proportionally, occupying the entire line.

On the previous release the behavior worked properly and the last 2 itens had same width of the previous row item.

Can you confirm if its the corret value to set on this property for that it back work again, or if its a bug on this release?

Regards 

Nelson Santos

**Comment by daniel-luberda** [comment]
You can enable old behavior with: `FlowUseAbsoluteLayoutInternally=true`. I'll try to fix this soon.

**Comment by NelsonSantos** [comment]
Hi Daniel...

Thank´s for your fast reply.

I have used FlowUseAbsoluteLayoutInternally=true and did not work!

I have tried with XF on iOS, tomorrow I will try on Android and see if works, and I tell you if it worked.

I will wait until you can fix it!!!

One more time, thankyou!

Best Regards...

Nelson Santos

**Comment by NelsonSantos** [comment]
Hi Daniel...

For your tests...

I have tested FlowUseAbsoluteLayoutInternally=true on Android and it worked!

But on iOS this not work.

Any questions or info, please contact me.

Regards...

Nelson Santos

**Comment by daniel-luberda** [comment]
Should be fixed in current stable :)

**Comment by kiranis** [comment]
Hi Daniel,

I have a FlowListView that is binded from a list of items, the list column number is set to 2, but I want to insert an extra item (ads) after each 4 items.

What I wanted to do is to column span that ad item dynamically but it didn't work with FlowColumnExpand property.

Appreciate your help on this matter.

Thanks!
Regards.
