### ISSUE TITLE
FlowListView doesn't update the 'View', when an Item of 'FlowItemsSource' changes

### ISSUE THREAD

**Issue by malokuS** [daniel-luberda/DLToolkit.Forms.Controls#38]
First of all, this is a great library, great job!

This problem doesn't show up when I use _Xamarin.Forms.ListView_ , but with the _FlowListView_ I can't get to update a specific Item on the ObservableCollection of the _FlowItemsSource_!

My environment is like this:

`DLToolkit.Forms.Controls.FlowListViev == v.2.0.2 /
Xamarin.Forms == v.2.3.3.163-pre3`

I've got an ItemModel Object, which implements `INotifyPropertyChanged`

I have a ViewModel which binds data to the FlowListView:
``` c# 
 public ExtendedObservableCollection<ItemModel> ListItems
        {
            get { return _ListItems; }
            set
            {
                _ListItems= value;
                OnPropertyChanged("ListItems");
            }
        }
```

The 'ExtendedObservableCollection' is basically an extension of the _ObservableCollection_ which notifies when an Item on that ObservableCollection changes.

My _FlowListView_ : 

``` xaml
<flv:FlowListView 
      x:Name="FriendsListView"
      FlowColumnCount="3" 
      SeparatorVisibility="None" 
      HasUnevenRows="true"
      FlowItemTappedCommand="{Binding ItemTappedCommand}" 
      FlowLastTappedItem="{Binding ItemTapped}"
      FlowItemsSource="{Binding ListItems}"
      FlowColumnMinWidth="100"
      RowHeight="-1">
      <flv:FlowListView.FlowColumnTemplate>
        <DataTemplate>
          <StackLayout
            Orientation="Vertical"
            HeightRequest="120"
            HorizontalOptions="CenterAndExpand"
            VerticalOptions="CenterAndExpand"
            Padding="5">
            <Label
              Text="{Binding Name}"
              TextColor="White"
              FontSize="20"
              LineBreakMode="TailTruncation"
              VerticalTextAlignment="Center"
              HorizontalTextAlignment="Center"/>
          </StackLayout>
        </DataTemplate>
      </flv:FlowListView.FlowColumnTemplate>
    </flv:FlowListView>
```

On my ViewModel I edit an Item which reflects the changes and everything works great, done testing/debug and the _'FlowItemsSource'_ updates the item, but the _FlowListView_ doesn't update the view (I don't see changes).

No errors on the log or anything! Everything looking smooth.

Am I missing something, or the _FlowItemsSource_ needs to be repopulated each time a change occurs(which costs a lot!) ?

Thanks in advance,
MalokuS

**Comment by malokuS** [comment]
Okay it seems that my _"ExtendedObservableCollection"_ was failing... -_-

You can close this "issue" :)

**Comment by daniel-luberda** [comment]
Somehow I missed that issue in my notifications, sorry for that. Nice that you resolved it :) Thanks! :)
