### ISSUE TITLE
Group w/ FlowTemplateselector

### ISSUE THREAD

**Issue by ryanherman** [daniel-luberda/DLToolkit.Forms.Controls#39]
If I put IsGroupingEnabled="true" then it doesn't seem to hit my TemplateSelector.  Is this something I'm doing wrong or it doesn't support?

**Comment by daniel-luberda** [comment]
I'll need full code. Here's grouping example: 

https://github.com/daniel-luberda/DLToolkit.Forms.Controls/blob/master/Samples/DLToolkitControlsSamples/SamplesFlowListView/GroupingPage.xaml

**Comment by ryanherman** [comment]
In my XAML I have:
`        <controls:FlowListView Grid.Row="2" FlowColumnCount="1" SeparatorVisibility="None" HasUnevenRows="true"
                               x:Name="ProjectFlow" BackgroundColor="Transparent" 
                               FlowUseAbsoluteLayoutInternally="True" IsGroupingEnabled="True">
        </controls:FlowListView>`

in my Code I have
`        private void LoadEvents(MessageHelper arg)
        {
            if (App.IotaConnect.isConnected() == false)
            {
                UserDialogs.Instance.Alert(AppResource.NoInternet, AppResource.NoInternetTitle,
                    AppResource.OK);
                return;
            }

            ProjectFlow.FlowColumnTemplate = new FlowTemplateSelector();
            ProjectFlow.FlowItemsSource = arg.EventListV2.events;

            LoadTabs(arg);
        }`

My FlowTemplateSelector() is:
`   public class FlowTemplateSelector : DLToolkit.Forms.Controls.FlowTemplateSelector
    {
        DataTemplate _eventCell = new DataTemplate(typeof(EventCellNew));
        DataTemplate _celebCell = new DataTemplate(typeof(CelebCell));
        DataTemplate _likeCell = new DataTemplate(typeof(LikeCell));

        protected override DataTemplate OnSelectTemplate(object item, int columnIndex, BindableObject container)
        {
            var type = item.GetType();
            if(type == typeof(ProjectById.Event))
            {
                    return _eventCell;
            }

            if (type == typeof(FanBase.Event))
            {
                return _celebCell;
            }

            return _eventCell;
        }
    }`

But I put a breakpoint on var type = item.GetType(); and it never gets to it.  If I put False for IsGroupingEnabled it will hit the breakpoint.

**Comment by daniel-luberda** [comment]
You are missing `FlowGroupDisplayBinding="{Binding Key}"`

**Comment by ryanherman** [comment]
I had it in there and it was still not hitting the template selector.

`        <controls:FlowListView Grid.Row="2" FlowColumnCount="1" SeparatorVisibility="None" HasUnevenRows="true"
                               x:Name="ProjectFlow" BackgroundColor="Transparent" 
                               FlowUseAbsoluteLayoutInternally="True" IsGroupingEnabled="True" FlowGroupDisplayBinding="{Binding Key}" FlowGroupShortNameBinding="{Binding Key}">
        </controls:FlowListView>`

**Comment by daniel-luberda** [comment]
Does your model have a valid `Key` property? You can clone repo and test sample project to see what is missing or put your code there.

**Comment by ryanherman** [comment]
Ah, I got it working thank you!

I love you plugins they are so well done!

**Comment by daniel-luberda** [comment]
Great, nice that you worked it out :)
