### ISSUE TITLE
Example without PageFactory

### ISSUE THREAD

**Issue by gviddy** [daniel-luberda/DLToolkit.Forms.Controls#4]
What's with the PageFactory and setting an ItemsSource ?

Could you please put up an example that does not require PageFactory or a BasePageModel for setting an items list ?

**Comment by gviddy** [comment]
Actually, don't worry as I have worked it out. FlowItemsSource is what I was needing.  :)

Thanks for the awesome library! :)

**Comment by daniel-luberda** [comment]
@gviddy, sorry for answering so late, I've been quite busy. Thanks, I am planning to release a new version with better examples soon.
