### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by ubaidsaeed** [daniel-luberda/DLToolkit.Forms.Controls#42]
I Installed the plugin in all three project. Portable,Droid and IOS from Nuget
I used SimplePage.xaml page code.
Project compile successfully but  when viewing on emulator it show this error
![capture](https://cloud.githubusercontent.com/assets/16667083/20309751/01db6e6a-ab6b-11e6-9754-9bb4b0bdf405.PNG)

**Comment by daniel-luberda** [comment]
- Be sure you're using correct namespaces in XAML 
- Call `FlowListView.Init()` somewhere
- Give some code, so I could help
