### ISSUE TITLE
Prevent column expanding

### ISSUE THREAD

**Issue by harbasevicAdnan** [daniel-luberda/DLToolkit.Forms.Controls#43]
How can I prevent column expanding if there is no other? Suppose it's should be easy, but I just can't do it.

**Comment by daniel-luberda** [comment]
Use `FlowColumndExpand="None"` which is a default one.

**Comment by harbasevicAdnan** [comment]
Thanks Daniel. I already tried this. I should mention that. But it doesn't work for me. Is it possible that something else overrides it? Here is my code.

```
<flv:FlowListView SeparatorVisibility="None"
        HasUnevenRows="true"
        FlowColumnCount="2"
	FlowColumnExpand="None"
	x:Name="listView" 
	Margin="10" 
        FlowItemTappedCommand="{Binding ChooseValueCommand}"
	FlowItemsSource="{Binding CardCollection}">
		<flv:FlowListView.FlowColumnTemplate>
			<DataTemplate>
			      <StackLayout Margin="7" BackgroundColor="{Binding Color}" VerticalOptions="Center" HeightRequest="140">
					<Label HorizontalOptions="Center" VerticalOptions="CenterAndExpand"
					Font="30" TextColor="Black" Text="{Binding DisplayValue}"></Label>
				</StackLayout>
			</DataTemplate>
		</flv:FlowListView.FlowColumnTemplate>
</flv:FlowListView>
```

**Comment by daniel-luberda** [comment]
I just checked this sample: https://github.com/daniel-luberda/DLToolkit.Forms.Controls/blob/master/Samples/DLToolkitControlsSamples/SamplesFlowListView/GroupingPage.xaml with replaced `FlowColumnExpand` property set to `None` and it works fine. Result: 

![simulator screen shot 18 nov 2016 02 51 53](https://cloud.githubusercontent.com/assets/13569983/20415656/fcd2f070-ad39-11e6-8060-e23745182663.png)

Maybe try to clean your `bin`/`obj` folders and enable XAML compilation.
