### ISSUE TITLE
Demo classes missing

### ISSUE THREAD

**Issue by AustinRichard** [daniel-luberda/DLToolkit.Forms.Controls#44]
The links to demo classes TagEntryViewPage.cs and TagEntryViewViewModel.cs are missing along with the android tenderer. Its not available in the solution as well.

**Comment by daniel-luberda** [comment]
I removed it temporarily. You can see oder ones here: https://github.com/daniel-luberda/DLToolkit.Forms.Controls/tree/1d3c5666ef0d49ef23324fbfb3519d3205e99e94/Examples

**Comment by daniel-luberda** [comment]
New samples provided.
