### ISSUE TITLE
FlowTappedBackgroundColor is not working

### ISSUE THREAD

**Issue by childy95** [daniel-luberda/DLToolkit.Forms.Controls#49]
i have set the FlowTappedBackgroundColor to red color, but when I tapped my item, the Background color seems to be remain the same default color. Any idea?

**Comment by planath** [comment]
Same for me 😢

**Comment by daniel-luberda** [comment]
You have to remove default os rows highlighting first: https://github.com/daniel-luberda/DLToolkit.Forms.Controls/tree/master/FlowListView#how-can-i-disable-entire-row-highlighting-when-tapped
