### ISSUE TITLE
TagEntryView with XAML : FileNotFoundException

### ISSUE THREAD

**Issue by Karine-GitHub** [daniel-luberda/DLToolkit.Forms.Controls#5]
Hi,

I try to use the TagEntryView in a Xaml page. I use the Cross-platform Xamarin Forms with MVVM pattern and Xaml page.
I add :
- the nuget package to all projects (PCL + each platform)
- namespace to PageContent

When I run, I have this exception : `System.IO.FileNotFoundException: Could not load file or assembly 'DLToolkit.Forms.Controls.TagEntryView' or one of its dependencies
`
How can I solve this issue please ?
 
My XAML looks like this 

	<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
          xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
           xmlns:behaviors="clr-namespace:Teedl.Mobile.Behaviors"
          x:Class="Teedl.Mobile.Views.ConnectionsView"
          xmlns:dltoolkit="clr-namespace:DLToolkit.Forms.Controls;assembly=DLToolkit.Forms.Controls.TagEntryView"
          Title="Connection Request">
	<ContentPage.Content>
    <ScrollView VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand">
      <StackLayout Orientation="Vertical" Padding="2">
          <dltoolkit:TagEntryView TagTappedCommand="{Binding RemoveTagCommand}" TagItems="{Binding ConnectionType}" Spacing="2" />
	...

**Comment by daniel-luberda** [comment]
If you're using XAML - only, you have to be very careful with Xamarin linker. 

Just add `var ignore = new TagEntryView()` somewhere in your code.
