### ISSUE TITLE
Implement CachingStrategy in FlowListView [Question]

### ISSUE THREAD

**Issue by childy95** [daniel-luberda/DLToolkit.Forms.Controls#50]
Is there any way to implement Caching Strategy in FlowListView? Thanks in advance! :)

**Comment by daniel-luberda** [comment]
It's already enabled by default.

**Comment by saraq85** [comment]
How can i set the Caching strategy? I want to change it to "RetainElement" in order to fix the issue for Android 7 (crash when scrolling the listview), is it possible?

**Comment by daniel-luberda** [comment]
Just use its alternate constructor: 

```C#
public FlowListView(ListViewCachingStrategy cachingStrategy) : base(cachingStrategy)
```

**Comment by 99hats** [comment]
This is a great library, except it is crashing on android when scrolling backwards (up instead of down)
I'm assuming this helps, but what does using the alternate constructor look like in XAML?

**Comment by johntsil** [comment]
Hello , how can i use caching strategy over XAML? When i use CachingStrategy ="RetainElement" my xaml doesnt even build. Thanks a lot

**Comment by RicardoMoraisPOR** [comment]
@johntsil @99hats a little late, but here is how you can pass a diferent CachingStrategy over XAML:

     <flv:FlowListView>
         <x:Arguments>
             <ListViewCachingStrategy>RetainElement</ListViewCachingStrategy>
         </x:Arguments>
     </flv:FlowListView>

And here are the docs on [Passing Arguments in XAML](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/passing-arguments)
