### ISSUE TITLE
Implement Selection

### ISSUE THREAD

**Issue by poseydonfba** [daniel-luberda/DLToolkit.Forms.Controls#51]
Is there a way to implement selecting multiple images for deletion?

**Comment by palla89** [comment]
I'd need this too!!

**Comment by andrepra** [comment]
I vote for this feature!

**Comment by daniel-luberda** [comment]
That would be a nice feature. Meanwhile, you can just use `TapGestureRecognizer` for that and handle it by yourself.

**Comment by daniel-luberda** [comment]
I'll close this one because it can be implemented using `TapGestureRecognizer` + custom views templates
