### ISSUE TITLE
How to column span an item inside FLowListView that is declared as 2 columned list?

### ISSUE THREAD

**Issue by kiranis** [daniel-luberda/DLToolkit.Forms.Controls#52]
Hi Daniel,

I have a FlowListView that is binded from a list of items, the list column number is set to 2, but I want to insert an extra item (ads) after each 4 items.

What I wanted to do is to column span that ad item dynamically but it didn't work with FlowColumnExpand property.

Appreciate your help on this matter.

Thanks!
Regards.

**Comment by daniel-luberda** [comment]
Hi @kiranis, 

Could you write more details? I can't understand what you want to achieve. Thanks :)

**Comment by mrtcofficial** [comment]
@daniel-luberda  i got same question ... See i set Flowlistviewcolumn = 2 and i got 20 Items to show but i want to show an Ad  in a after Every 4 items so for showing that ad i want to column span that row so my ad looks big ... 
this is what i want to achieve can you please tell us is it possible in FlowListView to ColumnSpan that specific row
