### ISSUE TITLE
Implement FlowScrollTo method

### ISSUE THREAD

**Issue by jonatanrinckus** [daniel-luberda/DLToolkit.Forms.Controls#54]
Is the ScrollTo working in the FlowListView?

**Comment by daniel-luberda** [comment]
Currently, you can only scroll to specific row number: 

```C#
var rowNumber = 5;
var list = flowListView.ItemsSource as IList<object>;
flowListView.ScrollTo(list[rowNumber], ScrollToPosition.Start, false);
```

When using grouping: 

```C#
var groupNumber = 1;
var rowNumber = 5;
var list = flowListView.ItemsSource as IList<object><IList<object>>;
flowListView.ScrollTo(list[groupNumber][rowNumber], ScrollToPosition.Start, false);
```

I can implement `FlowScrollTo` method in future. It would not be hard to do.

**Comment by fazil1979** [comment]
@daniel-luberda 

I have tried the above code but still scroll is set to top of list

**Comment by daniel-luberda** [comment]
It's implemented in: https://github.com/daniel-luberda/DLToolkit.Forms.Controls/commit/bef305e88dcd52f62ba5ab1f98e95e0a3678555e

**Comment by chatbaz** [comment]
Is this function MVVM pattern??
AND
I have downloaded the last Nuget but it doesn't have such a function
