### ISSUE TITLE
Android Release Mode - Images do not show on certain devices

### ISSUE THREAD

**Issue by mmajors** [daniel-luberda/DLToolkit.Forms.Controls#55]
Hello,

We have noticed that on some Android devices (Samsung Galaxy 5 and Google Pixel for example), images are not appearing in the cells in Release Mode.  We are calling FlowListView.Init().

Our grid is 2x5.  In Release mode, images appear in row 5, but they do not show for rows 1 - 4.

Thanks,
Marc

**Comment by daniel-luberda** [comment]
Hi @mmajors,
 
What are you using for displaying images?

**Comment by mmajors** [comment]
Hello again,

Here is our hierarchy:

FlowListView (Collection of Categories)
  FlowColumnTemplate
    DataTemplate
       Grid
         Image (We are binding the Source to an Image.  A Category has an Image)

**Comment by daniel-luberda** [comment]
If you use it XAML only, be sure to call `FlowListView.Init` somewhere as described here: https://github.com/daniel-luberda/DLToolkit.Forms.Controls/tree/master/FlowListView#faq
