### ISSUE TITLE
Getting build errors in SpanView

### ISSUE THREAD

**Issue by markti** [daniel-luberda/DLToolkit.Forms.Controls#56]
Did a fork and opened the solution. I'm seeing loads of build errors.

SpanView.Android has 8 errors.

![image](https://cloud.githubusercontent.com/assets/3155241/21547722/d1585934-cdb5-11e6-81ec-e144584d83e0.png)

SpanView.iOS has 1 error.

![image](https://cloud.githubusercontent.com/assets/3155241/21547736/e9e282f4-cdb5-11e6-80c9-c78d798fd65b.png)

**Comment by daniel-luberda** [comment]
It's fixed.
