### ISSUE TITLE
FlowListView and GroupHeader Template

### ISSUE THREAD

**Issue by SalahAtmitim** [daniel-luberda/DLToolkit.Forms.Controls#58]
Hi Daniel,
First of all, i want to thank you for this great component.

I have an issue with the GroupHeader Template. The group header does not appear even if i am using exaclty the equivalent code for a listView (i saw that you suggested this to the FlowListView users). I tried to do exactly as suggested by @BrunoBarrette in the xamarin forum : https://forums.xamarin.com/discussion/57953/flowlistview-group-header-template But it does not work for me. The group header is not appearing because of the binding " TextCell Text="{Binding Title}"  " is not working.
Here is my xaml code for the FlowlistView:

<flv:FlowListView x:Name="itemListView" FlowItemsSource="{Binding Items}" FlowColumnCount="3" SeparatorVisibility="None" 
                      IsGroupingEnabled="true" FlowGroupShortNameBinding="{Binding Title}" >

      <flv:FlowListView.FlowColumnTemplate>
        <DataTemplate>
          <StackLayout Margin ="14">
            <controls:ImageButton
                                 BackgroundColor="#ffffff"
                                 Font ="Medium"
                                 ImageHeightRequest="20"
                                 ImageWidthRequest="30"
                                 FontAttributes ="Bold"
                                 Text="{Binding Name}"
                                 TextColor="{Binding Color}"
                                 Source="{Binding Icon}">
            </controls:ImageButton>
          </StackLayout>
        </DataTemplate>
      </flv:FlowListView.FlowColumnTemplate>

      <flv:FlowListView.GroupHeaderTemplate>
        <DataTemplate>
          <TextCell Text="{Binding Title}"
          TextColor="#f35e20"
          DetailColor="#503026" />
        </DataTemplate>
      </flv:FlowListView.GroupHeaderTemplate>
      
  </flv:FlowListView>

Hope that there is a solution to make this working. Thank you again.

**Comment by nazgul87** [comment]
Hi, I had the same problem but I fixed it making this:

<flv:FlowListView SeparatorVisibility="None"
                          HasUnevenRows="false"
                          IsGroupingEnabled="True"
                          FlowItemsSource="{Binding Items}"
                          FlowGroupDisplayBinding="{Binding Path=Key}"
                          FlowGroupShortNameBinding="{Binding Path=Key}">
            <flv:FlowListView.GroupHeaderTemplate>
                <DataTemplate>
                    <ViewCell>
                        <StackLayout >
                            <Label Text="{Binding Path=Key}"></Label>
                        </StackLayout>
                    </ViewCell>
                </DataTemplate>
            </flv:FlowListView.GroupHeaderTemplate>
            <flv:FlowListView.FlowColumnTemplate>
                <DataTemplate>
                    <Label Text="{Binding Title}" />
                </DataTemplate>
            </flv:FlowListView.FlowColumnTemplate>
        </flv:FlowListView>

I set the FlowGroupDisplayBinding and FlowGroupShortNameBinding properties with the group "Key" value and in the FlowListView.GroupHeaderTemplate put a <ViewCell> inside the <DataTemplate>.

Note that the name of the group property is "Key", I do not know why, but it requires that name for show it.
After that, I saw the GroupHeaderTemplate.

I hope this help you.

Regards.

**Comment by daniel-luberda** [comment]
Full, working grouping example can be found here: https://github.com/daniel-luberda/DLToolkit.Forms.Controls/blob/master/Samples/DLToolkitControlsSamples/SamplesFlowListView/GroupingPage.xaml

@nazgul87 Thanks for help 👍

**Comment by SalahAtmitim** [comment]
Thank you very much @nazgul87 . I followed your solution and it works. 
@daniel-luberda  Thank you very much for this component and for all the examples in github.

**Comment by chrisfoulds** [comment]
@nazgul87 solution didn't work for me, after much playing this is what does so thought I would share.

```
	<flv:FlowListView 
			x:Name="flowListView" FlowColumnCount="1" SeparatorVisibility="None" RowHeight="-1" HasUnevenRows="true"
			FlowUseAbsoluteLayoutInternally="false" FlowColumnExpand="None"
			IsGroupingEnabled="true" 
            FlowGroupDisplayBinding="{Binding CatName}"
			FlowItemTappedCommand="{Binding ItemTappedCommand}" FlowLastTappedItem="{Binding LastTappedItem}"
			FlowItemsSource="{Binding Items}" >

            <flv:FlowListView.GroupHeaderTemplate>
                <DataTemplate>
                    <ViewCell>
                        <StackLayout BackgroundColor="#FF5722" HeightRequest="20" Padding="0,5,0,5" HorizontalOptions="FillAndExpand" VerticalOptions="CenterAndExpand">
                            <Label Margin="10,0,0,0" Text="{Binding Path=Key}" TextColor="White" VerticalTextAlignment="Center" FontSize="16" HorizontalOptions="FillAndExpand" VerticalOptions="CenterAndExpand">
                                <Label.FontFamily>                                  
                                    <OnPlatform x:TypeArguments="x:String">
                                        <OnPlatform.iOS>Roboto-Regular</OnPlatform.iOS>
                                        <OnPlatform.Android>Roboto-Regular.ttf#Roboto-Regular</OnPlatform.Android>
                                    </OnPlatform>
                                </Label.FontFamily>
                            </Label>
                        </StackLayout>
                    </ViewCell>
                </DataTemplate>
            </flv:FlowListView.GroupHeaderTemplate>
```
