### ISSUE TITLE
FlowListView - Partial ObservableCollection updates

### ISSUE THREAD

**Issue by mscrocdile** [daniel-luberda/DLToolkit.Forms.Controls#59]
Hello,
I use your great FlowListView this way:
`<flv:FlowListView FlowColumnMinWidth="175" HasUnevenRows="true" FlowItemsSource="{Binding AllItems}">`         
`<flv:FlowListView.FlowColumnTemplate>`
`           <DataTemplate>`
`               <Grid>`
`        	     <ffimageloading:CachedImage Source = "{Binding Img}" ...`
My problem is that if i insert new items (into zero position to have newest images on the top)  into AllItems(=ObservableCollection) then FlowListView is reloaded and it "flashes" and scroll position is set to the top.
What whould be perfect is that new images will be inserted and scroll position stays at the current position without flash effect.
Is that possible to do somehow?
Thank you

**Comment by daniel-luberda** [comment]
Hi @mscrocdile  Partial updates are not implemented yet. It shouldn't be hard to do it, but I'll need some time for this.

**Comment by fazil1979** [comment]
When it'll be updated we are facing terrible issues

**Comment by daniel-luberda** [comment]
It's now implemented.
