### ISSUE TITLE
Item height seems fixed

### ISSUE THREAD

**Issue by Haukinger** [daniel-luberda/DLToolkit.Forms.Controls#6]
How can I change the height of items in the list view?

Originally, I had a stacklayout in my template with two labels. When I add a new label, the last one is not shown, I only see the first two. Neither HeightRequest nor MinimumHeightRequest seems to work, whether on the contentview or the stacklayout inside.

**Comment by Karine-GitHub** [comment]
If you take a look to the DoHorizontalMesaure, you can see that the height property used here
if (rowCount > 1)
            {
                width = Math.Max(width, widthUsed);
                height = (height + Spacing) * rowCount - Spacing; // via MitchMilam 
            }

**Comment by daniel-luberda** [comment]
@Haukinger, sorry for answering so late, I've been quite busy. 

There are two options: 

- set FlowListView `RowHeight` property to a fixed value
- set `HasUnevenRows` property to `true`

Just the same as in standard Xamarin.Forms ListView.
