### ISSUE TITLE
Exception when use an Entry inside a FlowListView.FlowColumnTemplate

### ISSUE THREAD

**Issue by nazgul87** [daniel-luberda/DLToolkit.Forms.Controls#61]
Hello, first of all thank you very much for this wonderful control. It is awesome.

Well, I'm using FlowListView control in a Xamarin.Forms application to show an small list of items where I have to enable an entry to put some comments. 

The page has a button to save the comments after all the fields are filled.

After tap that button, I'm getting this error:
"**IllegalArgumentException: parameter must be a descendant of this view**"

I've noticed that issue happens when some entry is focused and the "save button" is tapped.
So my question is: Is there any way to fix this problem?

Any help will be really appreciated.

thanks in advance.

**Comment by nazgul87** [comment]
Well, after some hours of coding and test I finally found the solution.

The problem and solution is explained here:
http://stackoverflow.com/a/40659632/7407020

So, I only had to implement my custom IRecyclerListener to prevent the exception.

**Comment by daniel-luberda** [comment]
@nazgul87 Thanks for info! I'll mention this in README.md :) 👍
