### ISSUE TITLE
Crash when scrolling on Android 7.x (problem seen in example project too)

### ISSUE THREAD

**Issue by palla89** [daniel-luberda/DLToolkit.Forms.Controls#65]
Hi Daniel,

I have a problem with the FlowListView in my app. On Android 4.4 and Android 6 (Samsung galaxy s5) it works flawlessly, but on Android Nougat ( 7.x) my app crashes when scrolling after the screen has been filled with images. I also reproduced the problem in your sample application, in the Update items grouped example. 

What can I do to fix this?

Here there is the stack trace:

`  at Xamarin.Forms.Platform.Android.ListViewAdapter.GetView (System.Int32 position, Android.Views.View convertView, Android.Views.ViewGroup parent) [0x000ef] in C:\BuildAgent2\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\Renderers\ListViewAdapter.cs:223 
  at Android.Widget.BaseAdapter.n_GetView_ILandroid_view_View_Landroid_view_ViewGroup_ (System.IntPtr jnienv, System.IntPtr native__this, System.Int32 position, System.IntPtr native_convertView, System.IntPtr native_parent) [0x0001a] in /Users/builder/data/lanes/3511/501e63ce/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.Widget.BaseAdapter.cs:443 
  at (wrapper dynamic-method) System.Object:c292c97d-ebcc-4bd6-8985-3d51c66bc96e (intptr,intptr,int,intptr,intptr)`

<img width="1788" alt="schermata 2017-01-30 alle 13 13 04" src="https://cloud.githubusercontent.com/assets/12301205/22422666/de4392ac-e6ed-11e6-8449-362660c39250.png">

Maybe is it a problem with grouping Lists? I couldn't reproduce in the Simple Gallery section

EDIT: I think it's the grouping, because it's giving this error just in that examples!
EDIT2:  It seems an unresolved bug of Xamarin Forms with android 7, as noticed. 
https://bugzilla.xamarin.com/show_bug.cgi?id=51429
https://bugzilla.xamarin.com/show_bug.cgi?id=51645
https://bugzilla.xamarin.com/show_bug.cgi?id=51704

**Comment by daniel-luberda** [comment]
I'll close this one as it's fixed. Thanks :)

**Comment by timteam** [comment]
Hello @daniel-luberda,

First of all, I would like to thank you for the nice work you've done with the DLToolkit.
Nonetheless, For now, we have the DLToolkit.Forms.Controls.FlowListView available in v2.0.6 that still presents some issues with Android 7.x.
We are very looking forward to get our hands on your next stable release including the bug fix.

Best regards,
Timothée

**Comment by daniel-luberda** [comment]
@timteam It's Xamarin.Forms issue, what version of Forms do you use? I am afraid I cannot fix it on FlowListView's side. You must upgrade Xamarin.Forms package.

**Comment by timteam** [comment]
Thanks for your quick answer Daniel!

We are currently using the v2.3.4.270 of Xamarin.Forms which is supposed to be the last stable version.
Any idea?

**Comment by daniel-luberda** [comment]
Those Xamarin.Forms fixes are included in 2.3.5 pre packages.

**Comment by timteam** [comment]
I just tried your DLToolkitControlsSamples.Droid project with Xamarin.Forms in v2.3.5.256-pre6 and it seems to crash the same way on the "Advanced grouping example" as in our app. Can it be related to the same instability?

**Comment by palla89** [comment]
@timteam try to do a clean of the project, including deletion of the "bin" and "obj" folders, then close Xamarin Studio / Visual Studio, open it and try again, I've an app in production without this issue anymore, so the problem should be that.. Good luck!

**Comment by daniel-luberda** [comment]
`FlowListView` is based on a `ListView`, so same issues apply. As @palla89 said (thanks), please make sure you updated all Projects to the same Xamarin.Forms version, clean, remove `bin` / `obj` folders and rebuild.

**Comment by palla89** [comment]
No @daniel-luberda , thank you for the amazing work :)

unfortunately xamarin has still a lot of these kind of problem. Hope it gets better with time. @timteam don't forget to reopen the project after the steps daniel wrote in his previous post

**Comment by daniel-luberda** [comment]
There were several bugs, maybe they're fixed in 2.4?

**Comment by timteam** [comment]
@daniel-luberda Let's hope!
Thank you both for your time!

**Comment by robinmanuelthiel** [comment]
Had the same issue. Upgrading to Xamarin.Forms `2.4.0.269-pre2` solved it for me.
