### ISSUE TITLE
FlowListView happens to have a fixed height which cannot be changed.

### ISSUE THREAD

**Issue by ribas1a3** [daniel-luberda/DLToolkit.Forms.Controls#66]
I'm using the FlowListView and not able to change the height of the items. If I specify the HeightRequest property for the item inside DataTemplate then I get the height but the item only occupies certain height and the rest is blankspace. Is this a default behaviour?
<img width="318" alt="screen shot 2017-01-31 at 1 44 33 pm" src="https://cloud.githubusercontent.com/assets/4312269/22457002/901506aa-e7bb-11e6-9ed5-df542702bafd.png">

**Comment by daniel-luberda** [comment]
You need to:

- set `HasUnevenRows=false;` and  `RowHeight` to some value
OR: 
- set `HasUnevenRows=true;` and it should be calculated automatically

Just the same as Xamarin.Forms `ListView`

**Comment by ribas1a3** [comment]
Unfortunately this does not work. Tried both the options.

**Comment by daniel-luberda** [comment]
Did you try examples from our repository? There's no possibility to set RowHeight per row basis,  only as a global FlowListView property.

**Comment by darshan-rapidd** [comment]
Hi Daniel,

First of all thank you for this great plugin.

I have to set row height which is not happening, it's just taking the height same as a label text. I am new to Xamarin, please help

  <flv:FlowListView SeparatorVisibility="Default" RowHeight="60"  FlowColumnCount="3" FlowItemsSource="{Binding WebsiteList}">

    <flv:FlowListView.FlowColumnTemplate>
      <DataTemplate>
        <Grid Padding="3">
          <StackLayout>
            <Label x:Name="Label" HorizontalOptions="Fill" HorizontalTextAlignment="Center" VerticalOptions="End"
          BackgroundColor="Green" Text="{Binding WebsiteName}"/>
          </StackLayout>      
        </Grid>
      </DataTemplate>
    </flv:FlowListView.FlowColumnTemplate>

  </flv:FlowListView>

**Comment by ribas1a3** [comment]
@daniel-luberda : Yeah I have taken the samples from the repo, but like @darshan-rapidd  said, its weirdly setting the height to be constant. 
@darshan-rapidd  : As a temporary fix I've used this [solution](https://github.com/xamarin/xamarin-forms-book-samples/tree/master/Chapter26/PhotoWrap)

**Comment by darshan-rapidd** [comment]
Can someone please explain how FlowItemTappedCommand="{Binding ItemTappedCommand}" FlowLastTappedItem="{Binding LastTappedItem}" works ? I am not able to run the downloaded solution (All I get is failed to load project :( ), I am facing tough time trying to implement for ItemTappedCommand and ItemTappedCommand

**Comment by darshan-rapidd** [comment]
@ribas1a3 Thank you for the reply, Can you please tell me how are you able to get those boxes of same height in the attached image of yours. Is it a box view ? I want something similar to it with a text and an image inside that 

Thank You

**Comment by ribas1a3** [comment]
@darshan-rapidd : All I have used is Grid with background Color and Horizontal and Vertical Options as `FillAndExpand`.  But the issue I was facing was I could not set the height of this Grid. But you can use WrapGrid from the solution I gave. Also I'm guessing FlowLastTappedItem is bound to ViewModel command. Try removing the EventHandlers and testing first if things are not working accordingly.

**Comment by daniel-luberda** [comment]
> <flv:FlowListView SeparatorVisibility="Default" RowHeight="60" FlowColumnCount="3" FlowItemsSource="{Binding WebsiteList}">

You're setting `RowHeight` to a constant value. Instead you can just remove it and use `HasUnevenRows="true"` instead. Just the same as Xamarin.Forms `ListView`, exactly the same behaviour. 

> Can someone please explain how FlowItemTappedCommand="{Binding ItemTappedCommand}" FlowLastTappedItem="{Binding LastTappedItem}" works ? I am not able to run the downloaded solution (All I get is failed to load project :( ), I am facing tough time trying to implement for ItemTappedCommand and ItemTappedCommand

`ItemTappedCommand` just provides a `BindingContext` (your item data) as a command parameter. That's all. Just bind to it and use it like that: 

```
			ItemSelectedCommand = new Command((arg) =>
			{
				// arg is your list view item binding context (data model)
			});
```

**Comment by tonholis** [comment]
Hi guys!

I'm facing the same problem here.
I have a screen which is a form and it contains a FlowListView to display a grid of selected photos from device library. But FlowListView is taking a fixed height even when my image list is empty.

Here is a screenshot (red line is the FlowListView size):
![ice_screenshot_20170211-103622](https://cloud.githubusercontent.com/assets/5032355/22853806/93cfb324-f046-11e6-8162-505dc75cbb5f.png)

And here is my XAML:

```
<StackLayout HorizontalOptions="FillAndExpand">
	<!-- More controls... -->

	<controls:FlowListView 	FlowColumnCount="3"  SeparatorVisibility="None" HasUnevenRows="True">
		<controls:FlowListView.FlowColumnTemplate>
			<views:MyTemplateSelector/>
		</controls:FlowListView.FlowColumnTemplate>
	</controls:FlowListView>
	
	<!-- More controls... -->
</StackLayout>
```

**Comment by daniel-luberda** [comment]
Default `VerticalOptions` for FlowListView is `Fill`, just set it to `Start`
```

**Comment by tonholis** [comment]
>  Default VerticalOptions for FlowListView is Fill, just set it to Start. (Also in your cells)

@daniel-luberda I tried your suggestion but nothing changed. =(

**Comment by daniel-luberda** [comment]
Can you send me your sample code? I can update it.

**Comment by tonholis** [comment]
Hey @daniel-luberda , I created a demo here https://github.com/tonholis/xamarin-demo-FlowListView

**Comment by mrgithub** [comment]
In a similar vein, I would like to see the square cells i.e. width = height

**Comment by RobGibbens** [comment]
I'm having the same issue with the height of the `FlowListView`. It appears to be taking enough space for 8 rows when I only have data for four.

**Comment by snarf95** [comment]
I'm having the same issue with a basic use case. Something as simple as a horizontal listview is causing issues. The issue is the same with FlowListView taking up all available space (and more).

**Comment by daniel-luberda** [comment]
@RobGibbens @snarf95 

- Could you make a reproduction? 
- Do you set `HasUnevenRows` to `true` or `false`?
- Did you check FlowListView sample project?

**Comment by daniel-luberda** [comment]
FlowListView works just the same a ListView (it's a ListView derivative), so all layout specifics works just the same as Xamarin.Forms ListView. If you don't want to fill all available space, use something like Grid with ScrollView, etc

**Comment by Seddy24** [comment]
I'm having the same issue.  I would like it to display 2 rows of 3 images but it taking more space.  What am I doing wrong I have tried to set everything to Vertical Options="Start".  I have even tried setting the total record count to 6.  Any help would be much appreciated.

![image](https://user-images.githubusercontent.com/11354607/34216378-b13b7246-e56d-11e7-8977-b0a9795d85c1.png)

![image](https://user-images.githubusercontent.com/11354607/34216527-343f3f6a-e56e-11e7-92d8-64f76f4be029.png)

**Comment by daniel-luberda** [comment]
It's not FlowListView related (the same applies to Xamarin.Forms.ListView). Eg. Just insert `<BoxView VerticalOptions="FillAndExpand"/>` after `</controls:FlowListView>`.

**Comment by Seddy24** [comment]
Hmm same result after adding the BoxView.  I have stripped down to a basic StackLayout but still no luck the gap is still between the button and control.  Any way to remove the dead space?  Cool plugin by the way!

![image](https://user-images.githubusercontent.com/11354607/34218496-f0350b46-e573-11e7-8b8d-a7fa528cbcd8.png)

![image](https://user-images.githubusercontent.com/11354607/34218524-04aae38e-e574-11e7-96a8-4f7257b21262.png)

**Comment by LeoJHarris** [comment]
Im seeing this issue as well, considering the issue is still open I assume this is not fixed.

**Comment by CarLoOSX** [comment]
Same problem here, but only in android

**Comment by AnnuRArya** [comment]
Is there anyway we can reduce the `Spacing` between Column ?

**Comment by KevinAndrey96** [comment]
I have the same problem but only in iOs project

**Comment by marlonfal** [comment]
Hi, I solved this by doing [this](https://stackoverflow.com/a/68305743/9132056)
