### ISSUE TITLE
Infinite FlowListView on iOS after refreshing jumps to first item

### ISSUE THREAD

**Issue by UniorDev** [daniel-luberda/DLToolkit.Forms.Controls#67]
I have been created ListView that has infinite scrolling with help on ObservableRangeCollection. It works good on Android, but on iOS it jumps to start whenever it adds new items. Paginating is done with behavior. ListView is a FlowListView.

Here is an actual question:
http://stackoverflow.com/questions/41978469/infinite-listview-on-ios-after-refreshing-jumps-to-first-item?noredirect=1#comment71142155_41978469

**Comment by daniel-luberda** [comment]
I answered you on stackoverflow.

**Comment by UniorDev** [comment]
@daniel-luberda 
I will try it tomorrow, thank you.
