### ISSUE TITLE
Rendering nothing on Android 6.0

### ISSUE THREAD

**Issue by gabriel-fallen** [daniel-luberda/DLToolkit.Forms.Controls#68]
Hello!

Actually I have two issues and I suspect they are related.
I have a Xamarin.Forms application with `FlowListView` and `CachedImage`s. It should look like this:
![Android 5](https://i.imgur.com/6TO7Yba.png)

The first issue is when I tap on empty space in the last row right to the images. It becomes this:
![Android 5 after tap](https://i.imgur.com/WH8oblD.png)
The last two elements are invisible and do not react on taps anymore. After refresh they're back again.

On Android 6 I get this right away:
![Android 6](https://i.imgur.com/v6Svgj2.png)
There are two elements but they are invisible and do not react on taps. Refreshes do not help.

Now I suspect that both issues are essentially the same.

My DataTemplate looks like this:
```
<flv:FlowListView.FlowColumnTemplate>
    <DataTemplate>
        <ContentPage Content="{Binding Path='.'}" />
    </DataTemplate>
</flv:FlowListView.FlowColumnTemplate>
```
I.e. I have an `ObservableCollection` of `View`s (`Frame`s strictly speaking) and I want `FlowListView` to render them.

So maybe it's because I'm binding `View`s from model to XAML? I have the same issues with vanilla `ListView`.

Is there a straightforward way to populate `FlowListView` with already prepared `View`s? Or some workaround?

Thanks in advance!

**Comment by daniel-luberda** [comment]
Is it a typo or you really use `ContentPage` instead `ContentView`? 

```XML
<flv:FlowListView.FlowColumnTemplate>
    <DataTemplate>
        <ContentPage Content="{Binding Path='.'}" />
    </DataTemplate>
</flv:FlowListView.FlowColumnTemplate>
```

**Comment by gabriel-fallen** [comment]
Most likely a typo but I can't check it anymore. :)

I bet the problem was in passing the whole views through bindings.

Since then I've rewritten the code so the view gets constructed inside a template (in XAML) and now I bind only data elements (non-visual). Now everything works just right! :)

That cost me a little de-OOP-ization of view, I'm essentially using a switch now whereas I used subclasses before... But anyway.

Thanks for a great library by the way! :)

**Comment by daniel-luberda** [comment]
@gabriel-fallen Nice to hear that you worked it out, cheers and thanks! :)
