### ISSUE TITLE
FlowAutoColumnCount error on iOS

### ISSUE THREAD

**Issue by tamasszadvari** [daniel-luberda/DLToolkit.Forms.Controls#7]
If I set the FlowAutoColumnCount property to true on iOS, the app crashes immediately when the first element is added to the item source.
The FlowListView is inited at the app start, and the app crashes even if I implement the example (SimpleExamplePage) with the autocolumncount.

This is the error description in the HockeyApp crashlog:
" *** Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [nan 21.5]' "

**Comment by tamasszadvari** [comment]
The error also occurs, if the FlowAutoColumnCount property is set to false, and there's one FlowColumnSimpleTemplateSelector element in the FlowColumnsTemplates property's list.

**Comment by tamasszadvari** [comment]
It seems like that the source of the error is connected with the column with.
If I set the FlowAutoColumnCount to true, and doesn't set a FlowColumnDefaultMinimumWidth (or set it lesser or equal than the half of the page), and add 2 FlowColumnSimpleTemplateSelector to the FlowColumnsTemplates list, the error doesn't happen.
If the FlowColumnDefaultMinimumWidth is bigger than the half of the page, and there's two columns, the error happens independently from the FlowAutoColumnCount property.
If I set only 1 FlowColumnSimpleTemplateSelector, the error happens, no matter how I set the other properties.

**Comment by daniel-luberda** [comment]
@tamasszadvari , sorry for answering so late, I've been quite busy. Did you sort it out? I'll try to investigate it as I'm planning to release a new version of FlowListView. Thanks.

**Comment by tamasszadvari** [comment]
No problem, I compiled the library for myself with the PR modifications, and used that dll. :) I've not done a complete investigation, because the fix in the PR solved my problem. But regarding to the notes, that I've made here, and the fix that I've made, the problem has to be gone. (Every case that I've written here makes one column - if I'm correct -, and that caused an error.)

**Comment by daniel-luberda** [comment]
@tamasszadvari Thanks for the info! I'll close it and release a fix release then.
