### ISSUE TITLE
FlowListView is not updating when remove an item

### ISSUE THREAD

**Issue by tonholis** [daniel-luberda/DLToolkit.Forms.Controls#70]
Hi guys!

I have a simple scenario which a user can add and remove items from a ObservableCollection in MVVM app. 

I have an issue when I have two or more items and remove one item. The UI is not updating.
But when all items are removed from ObservableCollection, then the UI is updated clearing the list.

Take a look in the demo:
![listview](https://cloud.githubusercontent.com/assets/5032355/22976224/05a8765c-f371-11e6-93f4-b349ff4cdc6b.gif)

Here is the (resumed) code:

```
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
			 xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
			 xmlns:prism="clr-namespace:Prism.Mvvm;assembly=Prism.Forms"
			 prism:ViewModelLocator.AutowireViewModel="True"
			 xmlns:converters="clr-namespace:MyApp.Converters;assembly=MyApp"
			 x:Class="MyApp.Views.MyPage"
			 x:Name="MyPage">

	<ContentPage.Resources>
		<ResourceDictionary>
			<converters:UrlToImageSourceConverter x:Key="UrlToImageSource" />
		</ResourceDictionary>
	</ContentPage.Resources>

	<StackLayout HorizontalOptions="FillAndExpand" >

		<controls:FlowListView FlowColumnCount="3" 
							SeparatorVisibility="None" VerticalOptions="Start"
							HasUnevenRows="True"									
							FlowItemsSource="{Binding Images}">
			<controls:FlowListView.FlowColumnTemplate>
				<DataTemplate>
					<StackLayout Padding="0,0,0,0">
						<Image Source="{Binding Url, Converter=UrlToImageSource}" HeightRequest="90" Margin="0,5,0,5" />
						<Button Text="Remove" 
								Command="{Binding Source={x:Reference MyPage}, Path=BindingContext.RemoveImageCommand}" 
								CommandParameter="{Binding .}"/>
					</StackLayout>
				</DataTemplate>
			</controls:FlowListView.FlowColumnTemplate>
		</controls:FlowListView>

	</StackLayout>
</ContentPage>
```

```


public class MyPageViewModel : BindableBase
{
	private ObservableRangeCollection<MyImage> _imageList = new ObservableRangeCollection<MyImage>();


	public DelegateCommand<MyImage> RemoveImageCommand => new DelegateCommand<MyImage>(item => _imageList.Remove(item) );
	//...

	public ObservableRangeCollection<MyImage> Images
	{
		get { return _imageList; }
		set { SetProperty(ref _imageList, value); }
	}

}

public class MyImage
{
	public string Url { get; set; }
}

```

**Comment by NelsonSantos** [comment]
+1 Here!!

But, I maked a workaround to solve this until a solution:

1 - Remove the item
2 - Make a copy of your collection
3 - Set this copy in your ObservableCollection at your model

This make to FlowListItens.FlowItemsSource to know that have new collection and refresh the data.

Regards...

Nelson

**Comment by daniel-luberda** [comment]
@NelsonSantos @tonholis  Is it possible to get some kind of reproduction, so I could fix it? :)

**Comment by daniel-luberda** [comment]
Sorry, I didn't notice that @tonholis already included some code :) I'll try to debug / fix this by the weekend.

**Comment by tonholis** [comment]
No problem @daniel-luberda. Thanks!

**Comment by eduard1989** [comment]
Same problem, any updates?
Thanks

// EDDY

**Comment by GregorioCunha007** [comment]
Hey guys any updates on this problem @daniel-luberda ?

Thanks

**Comment by daniel-luberda** [comment]
Could you test the newest stable and see if you still experiencing it? There were a lot of changes.

**Comment by Andy74** [comment]
I experienced the same problem, that items were not removed, with version 2.0.4.
After Updating to version 2.0.6 I have the problem, that after adding new Items, the whole list will not be displayed. The same occurs, when deleting items.

**Comment by daniel-luberda** [comment]
@Andy74 On iOS / Android it works good. Generally, if speaking about UWP it may be Xamarin.Forms issue, as UWP ListView has some problems. Did you try to use the newest Xamarin.Forms prerelease nuget?

**Comment by Andy74** [comment]
@daniel-luberda : ok, with newest Xamarin.Forms prerelease (v2.4.0269-pre2) it works. thanks for your reply.

**Comment by daniel-luberda** [comment]
@Andy74 Nice to hear. I'll close this one then, cheers :)

**Comment by stevehatch** [comment]
This issue still exist today.  if you remove an item from the ObservabeCollection the UI list updates to remove the item but all items after it get messed up and don't bind correctly.  I've been able to work around this in previous projects by calling the ForceReload method but not even it helps with my current project.

**Comment by levelfivecoder** [comment]
I'm also facing this issue, Not yet fixed.

But it is happening only after opening the device keyboard

**Comment by levelfivecoder** [comment]
> +1 Here!!
> 
> But, I maked a workaround to solve this until a solution:
> 
> 1 - Remove the item
> 2 - Make a copy of your collection
> 3 - Set this copy in your ObservableCollection at your model
> 
> This make to FlowListItens.FlowItemsSource to know that have new collection and refresh the data.
> 
> Regards...
> 
> Nelson

not working
