### ISSUE TITLE
Wrong Row Height

### ISSUE THREAD

**Issue by ludiaz** [daniel-luberda/DLToolkit.Forms.Controls#71]
Hello buddies, this is my code:

    <flv:FlowListView
      x:Name="MyFlowListView"
      FlowColumnExpand="None"
      FlowColumnCount="2"
      SeparatorVisibility="None"
      HasUnevenRows="True"
      HorizontalOptions="FillAndExpand"
      VerticalOptions="Start"
      FlowItemsSource="{Binding myimages}"
      FlowItemTapped="ItemTapped">
     <flv:FlowListView.FlowColumnTemplate>

        <DataTemplate>
          <Grid
            VerticalOptions="Start"
            HorizontalOptions="Start"            
            Padding="3"
            RowSpacing="0"
            ColumnSpacing="0">           
            
            <Grid.RowDefinitions>
                <RowDefinition Height="*" />
            </Grid.RowDefinitions>         
            
            <Grid.ColumnDefinitions>
              <ColumnDefinition Width="*" />
            </Grid.ColumnDefinitions>

          <ffimageloading:CachedImage
	          Aspect="AspectFit"
            DownsampleToViewSize="true"
            CacheType="Disk"
            LoadingPlaceholder="Assets/imageLoading.gif"
            ErrorPlaceholder="Assets/imageError.png"
            Source="{Binding myimage}"/>         

          </Grid>
        </DataTemplate>
      </flv:FlowListView.FlowColumnTemplate>

    </flv:FlowListView>

And this is the shown (windows 10 mobile):
![wp_ss_20170215_0001](https://cloud.githubusercontent.com/assets/4026336/22991286/87b24514-f39a-11e6-856f-a033d07dd9f0.png)

Why this big space between rows?
* The black square is the space that the images are using. I can't show them here.
* Instead grid, i tried the stacklayout and the problem remains.
* In RowDefinition.Height, using "Auto"  or "*", the problem remains.

And this is showed in iOS Simulator (iPhone 6, iOS 10.2):
![ios](https://cloud.githubusercontent.com/assets/4026336/22991108/021a9f6e-f39a-11e6-9539-ebfb36f8b805.png)

* The black square is the space that the images are using. I can't show them here.

Same layout, but, very different in specific systems.
I have no ideia because this is happening!!!
Any help?

**Comment by hadhoryth** [comment]
The same problems, seems that it has fixed row height

**Comment by ludiaz** [comment]
Yes my friend.
I'm using fixed row height and now, it's ok.
But, we have many screen width, and this is not a better way.

For example:
* 2 columns in a big screen (10 inches), but the line with fixed size (240) left many 'blank space' at the screen.

The best approach is the row height be calculate automaticaly using the width of column.
I can do this using code (C#), but the best way is be done automaticaly.

(sorry for the english mistakes. i'm learning)

**Comment by hadhoryth** [comment]
@ludiaz I have played around a bit with sample app and find out that the problem with row height is related with Xamarin.Forms version. In my case I'm using pre-release. But you can solve you problem by using the "RetainElement" in caching strategy, because the default one is "RecycleElement"
In xaml it should be like that 
``` xml
<flv:FlowListView ....>
 <x:Arguments>
      <ListViewCachingStrategy>RetainElement</ListViewCachingStrategy>
  </x:Arguments>
</flv:FlowListView>
```

**Comment by daniel-luberda** [comment]
Hi @everyone

@ludiaz First of all, default `CachedImage` LayoutOptions are set to `Fill` container - it may be one of the reasons.

@hadhoryth `FlowListView` is a subclass of `ListView` so entire layout is dependent on it. If something works correctly with a `ListView` it also should work the same with `FlowListView` (with added columns of course).
