### ISSUE TITLE
Add Padding Property

### ISSUE THREAD

**Issue by YZahringer** [daniel-luberda/DLToolkit.Forms.Controls#73]
The Padding property would be useful in the component.

**Comment by daniel-luberda** [comment]
👍 Meanwhile, you can just use main view `Margin` / `Padding` properties.

**Comment by daniel-luberda** [comment]
I'll close this one as you can use Xamarin.Forms built in properties when defining Views. Cheers :)

**Comment by natsoragge** [comment]
I think this is not the same because if you use the view properties, the scrollbar position is affected. If one needs the padding to affect only the content, keeping the bar close to the screen border, the view properties won't work. I couldn't find a way to work around this problem ):

**Comment by YZahringer** [comment]
Same issue. Margin on ItemTemplate is not the best solution because it adds "double" margin between columns.
