### ISSUE TITLE
Removing Scrolling within the FlowListView

### ISSUE THREAD

**Issue by ChetCromer** [daniel-luberda/DLToolkit.Forms.Controls#74]
Is it possible to turn off scrolling within the FlowListView control? I have a ContentPage with content above the FlowListView, and my entire page is then wrapped inside a ScrollView. I'd like the FLV control to simply expand to it's fully needed height so it becomes part of the large scrolling page. It seems that it's currently autosizing to the height of the screen (even though it's Y coordinate is about half way down the screen when displayed), and not the height of the contents.

I've set my verticaloptions to FillAndExpand (and StartAndExpand) to no avail.

My code looks like this (a few things removed)

```

<ScrollView>
<StackLayout>
			<RelativeLayout>
				<Image x:Name="banner" Aspect="AspectFill" RelativeLayout.WidthConstraint="{ConstraintExpression Type=RelativeToParent, Property=Width, Factor=1}" />
				<StackLayout x:Name="bannerContentContainer" Padding="15" Spacing="10" RelativeLayout.WidthConstraint="{ConstraintExpression Type=RelativeToParent, Property=Width, Factor=1}">
					<local:HtmlLabel x:Name="bannerContent" />
					<Button Text="Listen Now" Clicked="OnPlayer" WidthRequest="250" HorizontalOptions="Start" />
				</StackLayout>
			</RelativeLayout>
			<StackLayout Padding="10" Spacing="10">
				<Label Text="{Binding title}" />
				<flv:FlowListView FlowColumnCount="{x:Static local:GlobalResources.FlowListViewColumns}" FlowItemsSource="{Binding resources}" SeparatorVisibility="None" FlowUseAbsoluteLayoutInternally="true" FlowItemTapped="OnChannel" HasUnevenRows="true" VerticalOptions="FillAndExpand">
					<flv:FlowListView.FlowColumnTemplate>
						<DataTemplate>
							<StackLayout Padding="5" Spacing="5">
								<Image Aspect="AspectFit" Source="{Binding images.thumbnail}" HeightRequest="{x:Static local:GlobalResources.ThumbnailImageHeight}" />
								<Label Text="{Binding title}" />
							</StackLayout>
						</DataTemplate>
					</flv:FlowListView.FlowColumnTemplate>
				</flv:FlowListView>
			</StackLayout>
		</StackLayout>
</ScrollView>
```

What I'd like to see happen is have the SLV size to the size of it's contents, and then I can just throw inside my "master" ScrollView.

**Comment by simonedoria** [comment]
up

**Comment by zanesc** [comment]
While @simonedoria set me in the right direction, his code is a bit off. Here is my version:

`public static double GetGridContainerHeight(double itemCount, double columnCount, int rowHeight)
		{
			var rowCount = Math.Ceiling(itemCount / columnCount);
			var padding = 5 * (rowCount + 1); // padding set in XAML on FlowColumnTemplate
			var height = (rowCount * rowHeight) + padding;
			return height;
		}`

**Comment by daniel-luberda** [comment]
I'll close this one as the answer is here. Thanks for info:)

**Comment by jamsoft** [comment]
Interesting, I have the exact opposite problem. I can't get it too scroll ...
