### ISSUE TITLE
SelectedItemTapped

### ISSUE THREAD

**Issue by predalpha** [daniel-luberda/DLToolkit.Forms.Controls#81]
Hello guys,

still trying your control. My tests are on UWP desktop.
When i tap an item in the flowlistview, it select the whole row. As your control derivate from Listview i can roger that. 

However the whole line is highlighted. Ive read  in your FAQ that we have to implement a custom renderer for each platform if we want to set the background color transparent. 

Why as Xam Listview can do that with ((ListView)sender).SelectedItem = null;

Moreover the line is push what is not UI friendly for a user. Could we freeze that animation ?

**Comment by zippo227** [comment]
@predalpha  Did you figure out how to prevent the whole row from highlighting on UWP?

**Comment by predalpha** [comment]
@zippo227 
No as the control derivate from listview, i think it s not possible.
I had to write a custom control with pain according to that -> [https://developer.xamarin.com/guides/xamarin-forms/user-interface/layouts/custom/](https://developer.xamarin.com/guides/xamarin-forms/user-interface/layouts/custom/)

**Comment by zippo227** [comment]
@predalpha After looking at this question, I found another question that had an answer that was little easier. https://github.com/daniel-luberda/DLToolkit.Forms.Controls/issues/31  I think @daniel-luberda needs to add the uwp answer to keep everyone from having to reinvent a solution for it.

**Comment by daniel-luberda** [comment]
I added it on control page. Also this: https://github.com/daniel-luberda/DLToolkit.Forms.Controls/commit/679876170f2ca3ce9c019db6570277ab867f0efb should help.
