### ISSUE TITLE
Changing FlowColumnCount causes problems on all platforms (Android, UWP, iOS)

### ISSUE THREAD

**Issue by tobbi007** [daniel-luberda/DLToolkit.Forms.Controls#82]
I am facing some issues when changing the FLowColumnCount when orientation changes.

Here is what i do:

**Xaml:**

```
<flv:FlowListView SeparatorVisibility="None"  FlowColumnCount="5" HasUnevenRows="False" x:Name="testlist" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand">
        <flv:FlowListView.FlowColumnTemplate>
            <DataTemplate>
                <Grid Padding="3">
                    <Grid.RowDefinitions>
                        <RowDefinition Height="100" />
                    </Grid.RowDefinitions>
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="*" />
                    </Grid.ColumnDefinitions>
                    <Image Source="{Binding MySource}" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand" Aspect="AspectFill"></Image>
                </Grid>
            </DataTemplate>
        </flv:FlowListView.FlowColumnTemplate>
    </flv:FlowListView>
```

**Change FlowColumnCount from 5 to 3 in OnSizeAllocated:**

```
protected override void OnSizeAllocated(double width, double height)
        {
            base.OnSizeAllocated(width, height);
            if (width > height)
                testlist.FlowColumnCount = 5;
            else
                testlist.FlowColumnCount = 3;
            testlist.ForceReload();
        }
```

**First the List appears to be correct:**

![screenshot_2017-03-15-17-30-40](https://cloud.githubusercontent.com/assets/509232/23960208/9f6116d6-09a7-11e7-9964-c08056d043ed.png)

**But when i rotate the device, this happens:**

![screenshot_2017-03-15-17-30-44](https://cloud.githubusercontent.com/assets/509232/23960234/adc1d738-09a7-11e7-8a1b-966205cda225.png)

This issue only happens, when there is a **certain number of views** in the list. I was able to reproduce it with **13** Views!
Also FlowUseAbsoluteLayoutInternally="True" did not help.
I have faced this issue on iOS and UWP aswell and could not figure out how to fix it.

To reproduce this I am using:
Xamarin Forms 2.3.3.193 (Latest Stable)
DLToolkit.Forms.Controls.FlowListView 2.0.4 (latest Stable -  NuGet)

I have also uploaded a sample Project [here](http://tobbi007.bplaced.net/transfer/FlowListTest.zip)
Thanks for your work, i really appreciate that this view exists.

**Comment by tobbi007** [comment]
I figured out that it only happens when you use 

```
public enum ListViewCachingStrategy
{
  RecycleElement // DEFAULT 
}
```

A workaround is to use
```
public enum ListViewCachingStrategy
{
  RetainElement
}
```

But scrolling performance decreases.

**Comment by cwjbowler** [comment]
I'm having the same issue changing the column count on orientation change.

How do you change the caching strategy? Do you have to create the control manually from code rather than using XAML, in order to access that additional constructor parameter?

**Comment by daniel-luberda** [comment]
Should be fixed in upcoming nuget release. Could you test it?

**Comment by tobbi007** [comment]
Sure. I will test it sometime this week. Thank you!

**Comment by tobbi007** [comment]
Sorry it took so long. Finally had time to test it. 
Seems to be working! Thank you.
