### ISSUE TITLE
Selected Item Style

### ISSUE THREAD

**Issue by azatrain** [daniel-luberda/DLToolkit.Forms.Controls#83]
Hi Daniel,

I've been using your flow list view control and it's been awesome so far.  I do have one question for you.  I've got a column template that looks like this:

`<flv:FlowListView.FlowColumnTemplate>
                            <DataTemplate>
                                <Button Text="{Binding Value}" FontSize="Micro" WidthRequest="100" VerticalOptions="Fill" Margin="0,0,10,0"
                                        Command="{Binding Source={x:Reference Name=InspectionWorkflow}, Path=BindingContext.SelectWorkflowItemValueCommand}" 
                                        CommandParameter="{Binding Value}" />
                            </DataTemplate>
                        </flv:FlowListView.FlowColumnTemplate>`

I'd like the selected item to "highlight" in some way so the user can easily determine which button they've clicked.  I tried setting the FlowTappedBackgroundColor, but that didn't seem to work.  Can you clue me in on the trick to get this sort of thing working?  Thanks ...

**Comment by UniorDev** [comment]
Maybe you will get lucky with this renderer that disable highlight. I think you could modify it to achieve what you need.  
https://github.com/daniel-luberda/DLToolkit.Forms.Controls/blob/master/Samples/Droid/Renderers/FlowListViewInternalCellRenderer.cs
https://github.com/daniel-luberda/DLToolkit.Forms.Controls/blob/master/Samples/iOS/Renderers/FlowListViewInternalCellRenderer.cs

**Comment by azatrain** [comment]
Thanks for the response Daniel.  Yeh that looks like it will get me where I need to go ...

**Comment by russlescai** [comment]
@azatrain hit the same issue, what did you need to do in FlowListViewInternalCellRendere to give it a background?

**Comment by azatrain** [comment]
@russlescai I haven't tried UniorDev's suggestions yet, but they looked pretty promising ...

**Comment by JeffB1** [comment]
Wouldn't happen to have a UWP renderer @UniorDev ? The Android one works great.

**Comment by UniorDev** [comment]
@JeffB1 Sorry, I don't have this one.

**Comment by daniel-luberda** [comment]
https://github.com/daniel-luberda/DLToolkit.Forms.Controls/blob/master/Samples/Windows/CustomListViewRenderer.cs
