### ISSUE TITLE
FlowItemTapped

### ISSUE THREAD

**Issue by extraPaul** [daniel-luberda/DLToolkit.Forms.Controls#88]
I have a FlowListView with a custom data template, which is binded to a list of items. If I specify a FlowItemTappedCommand everything works fine and the command executes from the ViewModel when an item is tapped. However if I change "FlowItemTappedCommand" to "FlowItemTapped" I get an error when trying to build. 

Here's the error I'm getting:
Unable to cast object of type 'Xamarin.Forms.Xaml.ElementNode' to type 'Xamarin.Forms.Xaml.ValueNode'.	

The only information I have is that the error comes from the XAML file where I made the change.

Does anyone have an idea of what could be causing this? 

Thanks!

**Comment by JoeDurand3** [comment]
Could you post some code?

**Comment by pradeepsj7** [comment]
@extraPaul  FlowItemTapped is event handler and you cannot assign Command to it.
