### ISSUE TITLE
Support for Windows Phone 8.1

### ISSUE THREAD

**Issue by stark-007** [daniel-luberda/DLToolkit.Forms.Controls#9]
Hi,
Just want to know if win phone 8 (not sliverlight) will be supported in the future. Thanks :)

**Comment by daniel-luberda** [comment]
It's already supported as the code is pure PCL. Are you having some problems with Windows 8.1?

**Comment by stark-007** [comment]
Hi Daniel, thanks for the information. Nuget package won't install on certain .net profiles but I haven't tried with newer versions. What I did was to fork the project and change target versions and it worked well for me since i also need to modify specific parts of flowlistview to support some features of my app. Thanks.

**Comment by daniel-luberda** [comment]
@stark-007 Thanks, I'll fix this in the upcoming release.
