### ISSUE TITLE
TapGestureRecognizers on iOS

### ISSUE THREAD

**Issue by JoeDurand3** [daniel-luberda/DLToolkit.Forms.Controls#91]
Hi - Trying to use a FlowListView on iOS with a stacklayout in the data template. The tap gesture is not working, and I'm not sure if its a combination of other properties or something else:

`<FLV:FlowListView  BackgroundColor="Transparent"
                              FlowColumnCount="2"
                              FlowItemsSource="{Binding NavigationGrid}"
                              HasUnevenRows="True"
                              SeparatorVisibility="None"
                              VerticalOptions="FillAndExpand"
                              IsPullToRefreshEnabled="False">
                <FLV:FlowListView.FlowColumnTemplate>
                    <DataTemplate>
                        <StackLayout Margin="0,10,0,10">
                            <StackLayout.GestureRecognizers>
                                <TapGestureRecognizer Command="{Binding ClickedCommand}"
                                                      CommandParameter="{Binding ClickedCommandParameter}"/>
                            </StackLayout.GestureRecognizers>
                            <Image Source="{Binding IconSourceLight}"
                                   WidthRequest="50"
                                   HeightRequest="50"/>
                            <Label HorizontalTextAlignment="Center"
                                   Text="{Binding DisplayName}"
                                   TextColor="{StaticResource ColorNeutralBright}"/>
                        </StackLayout>
                    </DataTemplate>
                </FLV:FlowListView.FlowColumnTemplate>
            </FLV:FlowListView>`

Any help would be appreciated!

**Comment by daniel-luberda** [comment]
I'll need more details / code to help you, if you provide them, I'll reopen the issue. Thanks.
