### ISSUE TITLE
Implementation from scratch not working

### ISSUE THREAD

**Issue by ProtocolNebula** [daniel-luberda/DLToolkit.Forms.Controls#92]
Hi.

Sorry for post here, I don't know where do it.

I'm trying to use the Toolkit (**FlowListView**, installed from **nuget**) but it don't work in any new project. I'm trying to do it from scratch (without xamvvm) and with xamvvm. When implementation works, screen leaves blank.

I tried to copy in a new project "SimplePage" and readapting.
I used ```FlowListView.Init();``` but fails too.

Can someone help me please? I lost round 5h trying the implementation.

Thanks in advanced :)

**Comment by thetombomb91** [comment]
Hello,

Assuming you are using a MVVM approach. So are you sure you are setting your FlowItemsSource properly. Based off the example provided here https://github.com/daniel-luberda/DLToolkit.Forms.Controls/blob/master/Samples/DLToolkitControlsSamples/SamplesFlowListView/SimplePage.xaml the FlowItemSource is bound to a model object on line 12. Then lines 14 through 19 are bound to properties within that model. So the Text="{Binding Title} is actually a property of the FlowItemsSource="{Binding Items}" Items object. 

I am assuming that is your problem and why you are coming up with a blank page. If not please try to explain more on your issue. 

Make sure that you have a flowitemsource set to one of your models and then in your flowcolumn template you are binding to properties of your model. 

I can throw a sample together for you if you if you can give me more details on what you are trying to do. Hope the above helps though.

**Comment by ProtocolNebula** [comment]
Hi.
Sorry for late.

I'm trying to create a new project without XAMVVM. I make a project here: https://github.com/ProtocolNebula/xamarin-dltoolkit-test

I tried again with XAMVVM but it don't **compile** (again), I don't know what more to do, I have not enough experience with Xamarin.

You would do me a great favor if you can help me or guide me to put it working.

Best regards.

**Comment by daniel-luberda** [comment]
You need to set correct `BindingContext` for you page. 

```C#
public App ()
{
    FlowListView.Init();

    InitializeComponent();
    MainPage = new DLToolkitTest.SampleMVVM() { BindingContext = new DLToolkitTest.SimplePageModel(); };
}
```
