### ISSUE TITLE
FlowAutoColumnCount

### ISSUE THREAD

**Issue by thimmy687** [daniel-luberda/DLToolkit.Forms.Controls#93]
Hello is the option FlowAutoColumnCount deprecated? 
it was in 1.0.6 available, but now it seems to be deleted?

```
/// <summary>
/// Gets or sets the minimum column width of FlowListView.
/// Currently used only with <c>FlowAutoColumnCount</c> option
/// </summary>
/// <value>The minimum column width.</value>
public double FlowColumnMinWidth
{
	get { return (double)GetValue(FlowColumnMinWidthProperty); }
	set { SetValue(FlowColumnMinWidthProperty, value); }
}
```

**Comment by dylin-maust** [comment]
+1

**Comment by daniel-luberda** [comment]
It's replaced with `FlowColumnCount` property. If you set it to null it works as auto column count. It's a default option now, so you don't need to set anything really to have auto column count.

**Comment by Ruddy2007** [comment]
At the moment if you do not set it (or set it to null) you get a null exception.
