### ISSUE TITLE
FlowColumnTemplate": Property does not exists

### ISSUE THREAD

**Issue by pradeepsj7** [daniel-luberda/DLToolkit.Forms.Controls#95]
Hi,

FlowColumnTemplate is giving exception,
Cannot assign property "FlowColumnTemplate": Property does not exists, or is not assignable, or mismatching type between value and property. 
Please help

**Comment by daniel-luberda** [comment]
I can't help you without some more details / code. The property is working fine. I'll reopen this after that. Thanks.
