### ISSUE TITLE
FlowItemTappedCommand not firing 

### ISSUE THREAD

**Issue by GregorioCunha007** [daniel-luberda/DLToolkit.Forms.Controls#97]
This is my XAML code 

    <controls:FlowListView x:Name="Board"
                      HasUnevenRows="true"
                      FlowColumnCount="3"
                      FlowItemTappedCommand="ExecuteActionCommand"
                      FlowColumnMinWidth="110">   
    ...
     </controls:FlowListView>

This is some code of my view model    

       public CardsExhibitViewModel()
        {
            ExecuteActionCommand = new Command<Card>(ExecuteAction);
        }

        public ICommand ExecuteActionCommand { get; private set; }
     
        private void ExecuteAction(Card card)
        {
            card.Action.ExecuteAction();
        }

What am I doing wrong ?

**Comment by savageqm** [comment]
Did you find a solution to this problem?

**Comment by GregorioCunha007** [comment]
Yes friend, it was a silly mistake. If you notice this line **"FlowItemTappedCommand="ExecuteActionCommand"** there's no binding expression, so I just added the **"{Binding ExecuteActionCommand}"** part and it worked out fine

**Comment by GregorioCunha007** [comment]
If this was not your problem I'll just leave you with my complete XAML of this part. Hope it helps

`<ScrollView>
            <controls:FlowListView x:Name="Board" HasUnevenRows="True"
                                   BackgroundColor="Black"
                                   FlowColumnCount="2"
                                   FlowItemTappedCommand="{Binding ExecuteActionCommand}"
                                   FlowColumnMinWidth="110"
                                   IsPullToRefreshEnabled="True"
                                   IsRefreshing="{Binding IsRefreshing}"
                                   RefreshCommand="{Binding RefreshViewCommand}"
                                   FlowItemsSource="{Binding Cards}">

                <controls:FlowListView.FlowColumnTemplate>
                    <DataTemplate>
                        <Grid Padding="5">
                            <Grid.RowDefinitions>
                                <RowDefinition Height="*" />
                            </Grid.RowDefinitions>
                            <Grid.ColumnDefinitions>
                                <ColumnDefinition Width="*" />
                            </Grid.ColumnDefinitions>
                            <ffimageloading:CachedImage HeightRequest="150" Aspect="AspectFill"
                                                        DownsampleHeight="150" DownsampleUseDipUnits="false"
                                                        Source="{Binding Representation}" />
                        </Grid>
                    </DataTemplate>
                </controls:FlowListView.FlowColumnTemplate>
            </controls:FlowListView>
        </ScrollView>`
