### ISSUE TITLE
Grid inside ViewCell

### ISSUE THREAD

**Issue by 7lol** [daniel-luberda/DLToolkit.Forms.Controls#98]
I used SimpleGalleryPage.xaml as my start-point.

I wanted to make template looks like :
`
<Grid Padding="3">
  <Grid.ColumnDefinitions>
    <ColumnDefinition Width="1*" />
    <ColumnDefinition Width="2*" />
  </Grid.ColumnDefinitions>
   <ffimageloading:CachedImage HeightRequest="100" Aspect="AspectFill" Grid.Column="0"
     DownsampleHeight="100" DownsampleUseDipUnits="false"  
     LoadingPlaceholder="image_loading.png" ErrorPlaceholder="image_error.png"
     Source="{Binding ImageUrl}"/>
    <Label x:Name="Label" HorizontalOptions="Fill" HorizontalTextAlignment="Center"
    Text="{Binding FileName}"  Grid.Column="1"/>
</Grid>
`
First its looking ok, then after like 0.5s it gets messy.

**Comment by daniel-luberda** [comment]
It may be some Xamarin.Forms layout system issue. We'll need some more code to help. I'll reopen it after that.
